// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountStatus.
const (
	Active      AccountStatus = "active"
	Blocked     AccountStatus = "blocked"
	Deactivated AccountStatus = "deactivated"
	Incomplete  AccountStatus = "incomplete"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Blocked:
		return true
	case Deactivated:
		return true
	case Incomplete:
		return true
	default:
		return false
	}
}

// Defines values for CreateRentalCancellationRequestActorKind.
const (
	CreateRentalCancellationRequestActorKindOperator CreateRentalCancellationRequestActorKind = "operator"
	CreateRentalCancellationRequestActorKindOwner    CreateRentalCancellationRequestActorKind = "owner"
	CreateRentalCancellationRequestActorKindPlatform CreateRentalCancellationRequestActorKind = "platform"
	CreateRentalCancellationRequestActorKindTenant   CreateRentalCancellationRequestActorKind = "tenant"
)

// Valid indicates whether the value is a known member of the CreateRentalCancellationRequestActorKind enum.
func (e CreateRentalCancellationRequestActorKind) Valid() bool {
	switch e {
	case CreateRentalCancellationRequestActorKindOperator:
		return true
	case CreateRentalCancellationRequestActorKindOwner:
		return true
	case CreateRentalCancellationRequestActorKindPlatform:
		return true
	case CreateRentalCancellationRequestActorKindTenant:
		return true
	default:
		return false
	}
}

// Defines values for DeclineRentalRequestReason.
const (
	ItemUnavailable DeclineRentalRequestReason = "item_unavailable"
	Other           DeclineRentalRequestReason = "other"
	OutsideSchedule DeclineRentalRequestReason = "outside_schedule"
	TermsMismatch   DeclineRentalRequestReason = "terms_mismatch"
)

// Valid indicates whether the value is a known member of the DeclineRentalRequestReason enum.
func (e DeclineRentalRequestReason) Valid() bool {
	switch e {
	case ItemUnavailable:
		return true
	case Other:
		return true
	case OutsideSchedule:
		return true
	case TermsMismatch:
		return true
	default:
		return false
	}
}

// Defines values for ListingCategory.
const (
	ListingCategoryAgricultural      ListingCategory = "agricultural"
	ListingCategoryElectric          ListingCategory = "electric"
	ListingCategoryHeavy             ListingCategory = "heavy"
	ListingCategoryLightConstruction ListingCategory = "light_construction"
	ListingCategoryManual            ListingCategory = "manual"
)

// Valid indicates whether the value is a known member of the ListingCategory enum.
func (e ListingCategory) Valid() bool {
	switch e {
	case ListingCategoryAgricultural:
		return true
	case ListingCategoryElectric:
		return true
	case ListingCategoryHeavy:
		return true
	case ListingCategoryLightConstruction:
		return true
	case ListingCategoryManual:
		return true
	default:
		return false
	}
}

// Defines values for ListingSize.
const (
	ListingSizeHeavy ListingSize = "heavy"
	ListingSizeLight ListingSize = "light"
)

// Valid indicates whether the value is a known member of the ListingSize enum.
func (e ListingSize) Valid() bool {
	switch e {
	case ListingSizeHeavy:
		return true
	case ListingSizeLight:
		return true
	default:
		return false
	}
}

// Defines values for ListingState.
const (
	Draft     ListingState = "draft"
	Paused    ListingState = "paused"
	Published ListingState = "published"
)

// Valid indicates whether the value is a known member of the ListingState enum.
func (e ListingState) Valid() bool {
	switch e {
	case Draft:
		return true
	case Paused:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for OperatorMode.
const (
	None     OperatorMode = "none"
	Optional OperatorMode = "optional"
	Required OperatorMode = "required"
)

// Valid indicates whether the value is a known member of the OperatorMode enum.
func (e OperatorMode) Valid() bool {
	switch e {
	case None:
		return true
	case Optional:
		return true
	case Required:
		return true
	default:
		return false
	}
}

// Defines values for PaymentIntentProvider.
const (
	Noop   PaymentIntentProvider = "noop"
	Stripe PaymentIntentProvider = "stripe"
)

// Valid indicates whether the value is a known member of the PaymentIntentProvider enum.
func (e PaymentIntentProvider) Valid() bool {
	switch e {
	case Noop:
		return true
	case Stripe:
		return true
	default:
		return false
	}
}

// Defines values for PaymentIntentStatus.
const (
	PaymentIntentStatusAuthorized     PaymentIntentStatus = "authorized"
	PaymentIntentStatusFailed         PaymentIntentStatus = "failed"
	PaymentIntentStatusRefunded       PaymentIntentStatus = "refunded"
	PaymentIntentStatusRequiresAction PaymentIntentStatus = "requires_action"
)

// Valid indicates whether the value is a known member of the PaymentIntentStatus enum.
func (e PaymentIntentStatus) Valid() bool {
	switch e {
	case PaymentIntentStatusAuthorized:
		return true
	case PaymentIntentStatusFailed:
		return true
	case PaymentIntentStatusRefunded:
		return true
	case PaymentIntentStatusRequiresAction:
		return true
	default:
		return false
	}
}

// Defines values for PaymentWebhookEventDataDepositState.
const (
	PaymentWebhookEventDataDepositStateCaptured PaymentWebhookEventDataDepositState = "captured"
	PaymentWebhookEventDataDepositStatePartial  PaymentWebhookEventDataDepositState = "partial"
	PaymentWebhookEventDataDepositStateReleased PaymentWebhookEventDataDepositState = "released"
)

// Valid indicates whether the value is a known member of the PaymentWebhookEventDataDepositState enum.
func (e PaymentWebhookEventDataDepositState) Valid() bool {
	switch e {
	case PaymentWebhookEventDataDepositStateCaptured:
		return true
	case PaymentWebhookEventDataDepositStatePartial:
		return true
	case PaymentWebhookEventDataDepositStateReleased:
		return true
	default:
		return false
	}
}

// Defines values for PaymentWebhookEventType.
const (
	PaymentAuthorized             PaymentWebhookEventType = "payment.authorized"
	PaymentChargebackCreated      PaymentWebhookEventType = "payment.chargeback_created"
	PaymentDepositCaptured        PaymentWebhookEventType = "payment.deposit_captured"
	PaymentDepositPartialCaptured PaymentWebhookEventType = "payment.deposit_partial_captured"
	PaymentDepositReleased        PaymentWebhookEventType = "payment.deposit_released"
	PaymentFailed                 PaymentWebhookEventType = "payment.failed"
	PaymentRefundSettled          PaymentWebhookEventType = "payment.refund_settled"
	PaymentRefunded               PaymentWebhookEventType = "payment.refunded"
)

// Valid indicates whether the value is a known member of the PaymentWebhookEventType enum.
func (e PaymentWebhookEventType) Valid() bool {
	switch e {
	case PaymentAuthorized:
		return true
	case PaymentChargebackCreated:
		return true
	case PaymentDepositCaptured:
		return true
	case PaymentDepositPartialCaptured:
		return true
	case PaymentDepositReleased:
		return true
	case PaymentFailed:
		return true
	case PaymentRefundSettled:
		return true
	case PaymentRefunded:
		return true
	default:
		return false
	}
}

// Defines values for PriceUnit.
const (
	Day  PriceUnit = "day"
	Hour PriceUnit = "hour"
)

// Valid indicates whether the value is a known member of the PriceUnit enum.
func (e PriceUnit) Valid() bool {
	switch e {
	case Day:
		return true
	case Hour:
		return true
	default:
		return false
	}
}

// Defines values for ReadyResponseStatus.
const (
	NotReady ReadyResponseStatus = "not_ready"
	Ready    ReadyResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyResponseStatus enum.
func (e ReadyResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for RentalCancellationActorKind.
const (
	RentalCancellationActorKindOperator RentalCancellationActorKind = "operator"
	RentalCancellationActorKindOwner    RentalCancellationActorKind = "owner"
	RentalCancellationActorKindPlatform RentalCancellationActorKind = "platform"
	RentalCancellationActorKindTenant   RentalCancellationActorKind = "tenant"
)

// Valid indicates whether the value is a known member of the RentalCancellationActorKind enum.
func (e RentalCancellationActorKind) Valid() bool {
	switch e {
	case RentalCancellationActorKindOperator:
		return true
	case RentalCancellationActorKindOwner:
		return true
	case RentalCancellationActorKindPlatform:
		return true
	case RentalCancellationActorKindTenant:
		return true
	default:
		return false
	}
}

// Defines values for RentalCancellationStateDeposit.
const (
	RentalCancellationStateDepositCaptured RentalCancellationStateDeposit = "captured"
	RentalCancellationStateDepositHeld     RentalCancellationStateDeposit = "held"
	RentalCancellationStateDepositPartial  RentalCancellationStateDeposit = "partial"
	RentalCancellationStateDepositReleased RentalCancellationStateDeposit = "released"
)

// Valid indicates whether the value is a known member of the RentalCancellationStateDeposit enum.
func (e RentalCancellationStateDeposit) Valid() bool {
	switch e {
	case RentalCancellationStateDepositCaptured:
		return true
	case RentalCancellationStateDepositHeld:
		return true
	case RentalCancellationStateDepositPartial:
		return true
	case RentalCancellationStateDepositReleased:
		return true
	default:
		return false
	}
}

// Defines values for RentalReceiptActorKind.
const (
	RentalReceiptActorKindOperator RentalReceiptActorKind = "operator"
	RentalReceiptActorKindOwner    RentalReceiptActorKind = "owner"
	RentalReceiptActorKindPlatform RentalReceiptActorKind = "platform"
	RentalReceiptActorKindTenant   RentalReceiptActorKind = "tenant"
)

// Valid indicates whether the value is a known member of the RentalReceiptActorKind enum.
func (e RentalReceiptActorKind) Valid() bool {
	switch e {
	case RentalReceiptActorKindOperator:
		return true
	case RentalReceiptActorKindOwner:
		return true
	case RentalReceiptActorKindPlatform:
		return true
	case RentalReceiptActorKindTenant:
		return true
	default:
		return false
	}
}

// Defines values for RentalReceiptDepositState.
const (
	RentalReceiptDepositStateCaptured RentalReceiptDepositState = "captured"
	RentalReceiptDepositStateHeld     RentalReceiptDepositState = "held"
	RentalReceiptDepositStatePartial  RentalReceiptDepositState = "partial"
	RentalReceiptDepositStateReleased RentalReceiptDepositState = "released"
)

// Valid indicates whether the value is a known member of the RentalReceiptDepositState enum.
func (e RentalReceiptDepositState) Valid() bool {
	switch e {
	case RentalReceiptDepositStateCaptured:
		return true
	case RentalReceiptDepositStateHeld:
		return true
	case RentalReceiptDepositStatePartial:
		return true
	case RentalReceiptDepositStateReleased:
		return true
	default:
		return false
	}
}

// Defines values for RentalState.
const (
	RentalStateAuthorized             RentalState = "authorized"
	RentalStateCancellationInProgress RentalState = "cancellation_in_progress"
	RentalStateCancelled              RentalState = "cancelled"
	RentalStateConfirmed              RentalState = "confirmed"
	RentalStateDeclined               RentalState = "declined"
	RentalStateExpired                RentalState = "expired"
	RentalStatePending                RentalState = "pending"
	RentalStateRefunded               RentalState = "refunded"
)

// Valid indicates whether the value is a known member of the RentalState enum.
func (e RentalState) Valid() bool {
	switch e {
	case RentalStateAuthorized:
		return true
	case RentalStateCancellationInProgress:
		return true
	case RentalStateCancelled:
		return true
	case RentalStateConfirmed:
		return true
	case RentalStateDeclined:
		return true
	case RentalStateExpired:
		return true
	case RentalStatePending:
		return true
	case RentalStateRefunded:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Capabilities AccountCapabilities `json:"capabilities"`
	DisplayName  string              `json:"display_name"`

	// Id Account id (UUID)
	Id     string        `json:"id"`
	Phone  string        `json:"phone"`
	Status AccountStatus `json:"status"`
}

// AccountStatus defines model for Account.Status.
type AccountStatus string

// AccountCapabilities defines model for AccountCapabilities.
type AccountCapabilities struct {
	// Publish Always false in F1 (owner onboarding is F2)
	Publish bool `json:"publish"`

	// Reserve True when profile is complete and account is active
	Reserve bool `json:"reserve"`
}

// AddBlockRequest defines model for AddBlockRequest.
type AddBlockRequest struct {
	EndsAt   time.Time `json:"ends_at"`
	Reason   *string   `json:"reason,omitempty"`
	StartsAt time.Time `json:"starts_at"`
}

// AvailabilityBlock defines model for AvailabilityBlock.
type AvailabilityBlock struct {
	CreatedAt time.Time          `json:"created_at"`
	EndsAt    time.Time          `json:"ends_at"`
	Id        openapi_types.UUID `json:"id"`
	ListingId openapi_types.UUID `json:"listing_id"`

	// Reason Free-text owner-side reason.
	Reason   string    `json:"reason"`
	StartsAt time.Time `json:"starts_at"`
}

// CategoryConfig defines model for CategoryConfig.
type CategoryConfig struct {
	Category        ListingCategory `json:"category"`
	DepositMinCents int             `json:"deposit_min_cents"`
	Size            ListingSize     `json:"size"`
}

// CreateListingRequest defines model for CreateListingRequest.
type CreateListingRequest struct {
	Category           ListingCategory  `json:"category"`
	Delivery           *ListingDelivery `json:"delivery,omitempty"`
	DepositCents       int              `json:"deposit_cents"`
	Description        string           `json:"description"`
	HeavyLegalCession  *bool            `json:"heavy_legal_cession,omitempty"`
	MinLeadTimeHours   int              `json:"min_lead_time_hours"`
	Operator           ListingOperator  `json:"operator"`
	Photos             *[]string        `json:"photos,omitempty"`
	PickupCity         string           `json:"pickup_city"`
	PickupNeighborhood string           `json:"pickup_neighborhood"`
	PriceAmountCents   int              `json:"price_amount_cents"`
	PriceUnit          PriceUnit        `json:"price_unit"`
	Rules              *ListingRules    `json:"rules,omitempty"`
	Title              string           `json:"title"`
}

// CreateRentalCancellationRequest defines model for CreateRentalCancellationRequest.
type CreateRentalCancellationRequest struct {
	ActorKind CreateRentalCancellationRequestActorKind `json:"actor_kind"`

	// ProcessorOperationId Optional PSP-side operation id that triggered the
	// cancellation (refund, chargeback). When the request comes
	// from a webhook handler, this is the event id; idempotent
	// on (rental_id, actor_kind, processor_operation_id).
	ProcessorOperationId *string `json:"processor_operation_id,omitempty"`
	Reason               *string `json:"reason,omitempty"`
}

// CreateRentalCancellationRequestActorKind defines model for CreateRentalCancellationRequest.ActorKind.
type CreateRentalCancellationRequestActorKind string

// CreateRentalRequest defines model for CreateRentalRequest.
type CreateRentalRequest struct {
	EndsAt                time.Time          `json:"ends_at"`
	ListingId             openapi_types.UUID `json:"listing_id"`
	OperatorTermsAccepted bool               `json:"operator_terms_accepted"`
	StartsAt              time.Time          `json:"starts_at"`
	WithOperator          bool               `json:"with_operator"`
}

// DeactivateAccountRequest defines model for DeactivateAccountRequest.
type DeactivateAccountRequest struct {
	// Confirm Example: true
	Confirm bool `json:"confirm"`
}

// DeclineRentalRequest defines model for DeclineRentalRequest.
type DeclineRentalRequest struct {
	Reason *DeclineRentalRequestReason `json:"reason,omitempty"`
}

// DeclineRentalRequestReason defines model for DeclineRentalRequest.Reason.
type DeclineRentalRequestReason string

// Error defines model for Error.
type Error struct {
	// Code Example: unauthorized
	Code string `json:"code"`

	// Message Localized human message
	Message string `json:"message"`

	// MessageKey Example: auth.unauthorized
	MessageKey string `json:"message_key"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Example: canteiro
	Service *string `json:"service,omitempty"`

	// Status Example: ok
	Status string `json:"status"`
}

// Listing defines model for Listing.
type Listing struct {
	Category     ListingCategory `json:"category"`
	CreatedAt    *time.Time      `json:"created_at,omitempty"`
	Delivery     ListingDelivery `json:"delivery"`
	DepositCents int             `json:"deposit_cents"`
	Description  string          `json:"description"`

	// HeavyLegalCession Required true for `heavy` category when published.
	HeavyLegalCession  *bool              `json:"heavy_legal_cession,omitempty"`
	Id                 openapi_types.UUID `json:"id"`
	MinLeadTimeHours   int                `json:"min_lead_time_hours"`
	Operator           ListingOperator    `json:"operator"`
	OwnerAccountId     openapi_types.UUID `json:"owner_account_id"`
	Photos             []string           `json:"photos"`
	PickupCity         string             `json:"pickup_city"`
	PickupNeighborhood string             `json:"pickup_neighborhood"`
	PriceAmountCents   int                `json:"price_amount_cents"`
	PriceUnit          PriceUnit          `json:"price_unit"`
	Rules              ListingRules       `json:"rules"`
	Size               *ListingSize       `json:"size,omitempty"`
	State              ListingState       `json:"state"`
	Title              string             `json:"title"`
	UpdatedAt          *time.Time         `json:"updated_at,omitempty"`
}

// ListingCategory defines model for ListingCategory.
type ListingCategory string

// ListingDelivery defines model for ListingDelivery.
type ListingDelivery struct {
	// Coverage Free-text delivery area; non-empty when enabled.
	Coverage string `json:"coverage"`
	Enabled  bool   `json:"enabled"`
}

// ListingOperator defines model for ListingOperator.
type ListingOperator struct {
	HourlyRateCents *int              `json:"hourly_rate_cents,omitempty"`
	Identity        *OperatorIdentity `json:"identity,omitempty"`
	MinHours        *int              `json:"min_hours,omitempty"`
	Mode            OperatorMode      `json:"mode"`
}

// ListingPage defines model for ListingPage.
type ListingPage struct {
	Items    []PublicListing `json:"items"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
	Total    int             `json:"total"`
}

// ListingRules defines model for ListingRules.
type ListingRules struct {
	DocumentRequired   *bool `json:"document_required,omitempty"`
	ExperienceRequired *bool `json:"experience_required,omitempty"`
	MinAge             *int  `json:"min_age,omitempty"`
	TravelRestricted   *bool `json:"travel_restricted,omitempty"`
}

// ListingSize defines model for ListingSize.
type ListingSize string

// ListingSnapshot defines model for ListingSnapshot.
type ListingSnapshot struct {
	Category         ListingCategory    `json:"category"`
	DepositCents     int                `json:"deposit_cents"`
	MinLeadTimeHours *int               `json:"min_lead_time_hours,omitempty"`
	Operator         SnapshotOperator   `json:"operator"`
	OwnerId          openapi_types.UUID `json:"owner_id"`
	PickupCity       *string            `json:"pickup_city,omitempty"`
	PriceAmountCents int                `json:"price_amount_cents"`
	PriceUnit        PriceUnit          `json:"price_unit"`
	Title            string             `json:"title"`
}

// ListingState defines model for ListingState.
type ListingState string

// OperatorIdentity defines model for OperatorIdentity.
type OperatorIdentity struct {
	// IsOwner True when the operator is the listing owner.
	IsOwner bool   `json:"is_owner"`
	Name    string `json:"name"`
	Phone   string `json:"phone"`
}

// OperatorMode defines model for OperatorMode.
type OperatorMode string

// OwnerOnboarding defines model for OwnerOnboarding.
type OwnerOnboarding struct {
	// PayoutKind Opaque payout kind (e.g. pix, bank).
	PayoutKind      *string    `json:"payout_kind,omitempty"`
	PayoutLast4     *string    `json:"payout_last4,omitempty"`
	PayoutSet       bool       `json:"payout_set"`
	TermsAccepted   bool       `json:"terms_accepted"`
	TermsAcceptedAt *time.Time `json:"terms_accepted_at,omitempty"`
	TermsVersion    string     `json:"terms_version"`
}

// PaymentIntent defines model for PaymentIntent.
type PaymentIntent struct {
	AmountCents        int                   `json:"amount_cents"`
	Attempt            int                   `json:"attempt"`
	CreatedAt          *time.Time            `json:"created_at,omitempty"`
	DepositCents       int                   `json:"deposit_cents"`
	ExpectedTotalCents int                   `json:"expected_total_cents"`
	FailureCode        *string               `json:"failure_code,omitempty"`
	FailureMessage     *string               `json:"failure_message,omitempty"`
	Id                 openapi_types.UUID    `json:"id"`
	IdempotencyKey     string                `json:"idempotency_key"`
	Provider           PaymentIntentProvider `json:"provider"`
	ProviderPaymentId  *string               `json:"provider_payment_id,omitempty"`
	RentalId           openapi_types.UUID    `json:"rental_id"`
	Status             PaymentIntentStatus   `json:"status"`
	UpdatedAt          *time.Time            `json:"updated_at,omitempty"`
}

// PaymentIntentProvider defines model for PaymentIntent.Provider.
type PaymentIntentProvider string

// PaymentIntentStatus defines model for PaymentIntent.Status.
type PaymentIntentStatus string

// PaymentWebhookEvent defines model for PaymentWebhookEvent.
type PaymentWebhookEvent struct {
	Data struct {
		AmountCents int `json:"amount_cents"`

		// ChargebackReason Set only on chargeback events.
		ChargebackReason *string `json:"chargeback_reason,omitempty"`
		DepositCents     *int    `json:"deposit_cents,omitempty"`

		// DepositState F4 deposit event — only set for deposit.* and
		// refund_settled/chargeback events. Required for
		// deposit events; ignored otherwise.
		DepositState    *PaymentWebhookEventDataDepositState `json:"deposit_state,omitempty"`
		FailureCode     *string                              `json:"failure_code,omitempty"`
		FailureMessage  *string                              `json:"failure_message,omitempty"`
		PaymentIntentId *openapi_types.UUID                  `json:"payment_intent_id,omitempty"`
		RentalId        openapi_types.UUID                   `json:"rental_id"`
	} `json:"data"`
	Id   string                  `json:"id"`
	Type PaymentWebhookEventType `json:"type"`
}

// PaymentWebhookEventDataDepositState F4 deposit event — only set for deposit.* and
// refund_settled/chargeback events. Required for
// deposit events; ignored otherwise.
type PaymentWebhookEventDataDepositState string

// PaymentWebhookEventType defines model for PaymentWebhookEvent.Type.
type PaymentWebhookEventType string

// PriceUnit defines model for PriceUnit.
type PriceUnit string

// PublicCalendar defines model for PublicCalendar.
type PublicCalendar struct {
	Blocks []struct {
		EndsAt   time.Time `json:"ends_at"`
		StartsAt time.Time `json:"starts_at"`
	} `json:"blocks"`
	ListingId        openapi_types.UUID `json:"listing_id"`
	MinLeadTimeHours int                `json:"min_lead_time_hours"`
}

// PublicListing defines model for PublicListing.
type PublicListing struct {
	Category                ListingCategory    `json:"category"`
	CreatedAt               time.Time          `json:"created_at"`
	DeliveryEnabled         *bool              `json:"delivery_enabled,omitempty"`
	DepositCents            int                `json:"deposit_cents"`
	Description             string             `json:"description"`
	Id                      openapi_types.UUID `json:"id"`
	MinLeadTimeHours        int                `json:"min_lead_time_hours"`
	OperatorHourlyRateCents *int               `json:"operator_hourly_rate_cents,omitempty"`
	OperatorMode            *OperatorMode      `json:"operator_mode,omitempty"`
	Photos                  []string           `json:"photos"`
	PickupCity              string             `json:"pickup_city"`
	PickupNeighborhood      string             `json:"pickup_neighborhood"`
	PriceAmountCents        int                `json:"price_amount_cents"`
	PriceUnit               PriceUnit          `json:"price_unit"`
	Rules                   ListingRules       `json:"rules"`
	Size                    ListingSize        `json:"size"`
	Title                   string             `json:"title"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	// Message Localized human message
	Message string `json:"message"`

	// MessageKey Stable i18n key
	//
	// Example: ready.ok
	MessageKey string `json:"message_key"`

	// Service Example: canteiro
	Service *string             `json:"service,omitempty"`
	Status  ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// Rental defines model for Rental.
type Rental struct {
	AcceptanceDeadlineAt  *time.Time         `json:"acceptance_deadline_at,omitempty"`
	CommissionCents       int                `json:"commission_cents"`
	ConfirmedAt           *time.Time         `json:"confirmed_at,omitempty"`
	CreatedAt             time.Time          `json:"created_at"`
	DeclineReason         *string            `json:"decline_reason,omitempty"`
	DeclinedAt            *time.Time         `json:"declined_at,omitempty"`
	DepositCents          int                `json:"deposit_cents"`
	EndsAt                time.Time          `json:"ends_at"`
	Id                    openapi_types.UUID `json:"id"`
	IntentKey             string             `json:"intent_key"`
	ListingId             openapi_types.UUID `json:"listing_id"`
	ListingSnapshot       ListingSnapshot    `json:"listing_snapshot"`
	OperatorCents         int                `json:"operator_cents"`
	OperatorPayoutCents   int                `json:"operator_payout_cents"`
	OperatorTermsAccepted bool               `json:"operator_terms_accepted"`
	OwnerPayoutCents      int                `json:"owner_payout_cents"`
	RentCents             int                `json:"rent_cents"`
	StartsAt              time.Time          `json:"starts_at"`
	State                 RentalState        `json:"state"`
	TenantAccountId       openapi_types.UUID `json:"tenant_account_id"`
	UpdatedAt             time.Time          `json:"updated_at"`
	WithOperator          bool               `json:"with_operator"`
}

// RentalCancellation defines model for RentalCancellation.
type RentalCancellation struct {
	ActorAccountId                       openapi_types.UUID          `json:"actor_account_id"`
	ActorKind                            RentalCancellationActorKind `json:"actor_kind"`
	CancellationFeeCents                 int                         `json:"cancellation_fee_cents"`
	DepositCaptureCents                  int                         `json:"deposit_capture_cents"`
	DepositPartialCaptureCents           int                         `json:"deposit_partial_capture_cents"`
	DepositReleaseCents                  int                         `json:"deposit_release_cents"`
	Id                                   openapi_types.UUID          `json:"id"`
	IssuedAt                             time.Time                   `json:"issued_at"`
	OperatorPayoutCentsAfterCancellation int                         `json:"operator_payout_cents_after_cancellation"`
	OwnerPayoutCentsAfterCancellation    int                         `json:"owner_payout_cents_after_cancellation"`
	ProcessorOperationId                 *string                     `json:"processor_operation_id,omitempty"`
	RentalId                             openapi_types.UUID          `json:"rental_id"`

	// ReversalReason Set when this cancellation is a chargeback reversal.
	ReversalReason    *string                        `json:"reversal_reason,omitempty"`
	StateDeposit      RentalCancellationStateDeposit `json:"state_deposit"`
	TenantRefundCents int                            `json:"tenant_refund_cents"`

	// WindowApplied Declarative F4 window code (see RentalReceipt.window_applied).
	WindowApplied string `json:"window_applied"`
}

// RentalCancellationActorKind defines model for RentalCancellation.ActorKind.
type RentalCancellationActorKind string

// RentalCancellationStateDeposit defines model for RentalCancellation.StateDeposit.
type RentalCancellationStateDeposit string

// RentalQuoteOut defines model for RentalQuoteOut.
type RentalQuoteOut struct {
	CommissionBaseCents int                `json:"commission_base_cents"`
	CommissionCents     int                `json:"commission_cents"`
	DepositCents        int                `json:"deposit_cents"`
	OperatorCents       int                `json:"operator_cents"`
	OperatorPayoutCents int                `json:"operator_payout_cents"`
	OwnerPayoutCents    int                `json:"owner_payout_cents"`
	RentCents           int                `json:"rent_cents"`
	RentalId            openapi_types.UUID `json:"rental_id"`
	TotalCents          int                `json:"total_cents"`
}

// RentalReceipt defines model for RentalReceipt.
type RentalReceipt struct {
	// ActorKind Who triggered the cancellation (F4). Empty when no cancellation.
	ActorKind *RentalReceiptActorKind `json:"actor_kind,omitempty"`

	// CancellationFeeCents F4 cancellation fee (10% of rent in the >=24h window).
	CancellationFeeCents       *int       `json:"cancellation_fee_cents,omitempty"`
	CancellationIssuedAt       *time.Time `json:"cancellation_issued_at,omitempty"`
	CommissionBaseCents        int        `json:"commission_base_cents"`
	CommissionCents            int        `json:"commission_cents"`
	DepositCaptureCents        *int       `json:"deposit_capture_cents,omitempty"`
	DepositCents               int        `json:"deposit_cents"`
	DepositPartialCaptureCents *int       `json:"deposit_partial_capture_cents,omitempty"`
	DepositReleaseCents        *int       `json:"deposit_release_cents,omitempty"`

	// DepositState F4 deposit state in the receipt: released (default), captured
	// (fully), partial (partially), held (still held; F5 will decide).
	DepositState        *RentalReceiptDepositState `json:"deposit_state,omitempty"`
	IssuedAt            time.Time                  `json:"issued_at"`
	ListingSnapshot     ListingSnapshot            `json:"listing_snapshot"`
	OperatorCents       int                        `json:"operator_cents"`
	OperatorPayoutCents int                        `json:"operator_payout_cents"`

	// OperatorPayoutCentsAfterCancellation Operator payout (third-party operator; zero when operator=owner).
	OperatorPayoutCentsAfterCancellation *int `json:"operator_payout_cents_after_cancellation,omitempty"`
	OwnerPayoutCents                     int  `json:"owner_payout_cents"`

	// OwnerPayoutCentsAfterCancellation Owner payout net of commission (zero when rent fully refunded).
	OwnerPayoutCentsAfterCancellation *int `json:"owner_payout_cents_after_cancellation,omitempty"`

	// ProcessorOperationId PSP-side operation id (refund, chargeback, deposit capture).
	ProcessorOperationId *string            `json:"processor_operation_id,omitempty"`
	RentCents            int                `json:"rent_cents"`
	RentalId             openapi_types.UUID `json:"rental_id"`
	TenantAccountId      openapi_types.UUID `json:"tenant_account_id"`

	// TenantRefundCents Net amount refunded to the tenant after fee + commission.
	TenantRefundCents *int `json:"tenant_refund_cents,omitempty"`
	TotalCents        int  `json:"total_cents"`

	// WindowApplied F4 declarative window code (e.g. "tenant.pre_accept",
	// "tenant.ge_24h", "tenant.lt_24h", "tenant.after_start",
	// "owner.pre_pickup", "owner.after_start").
	//
	//
	// Example: tenant.ge_24h
	WindowApplied  *string   `json:"window_applied,omitempty"`
	WindowEndsAt   time.Time `json:"window_ends_at"`
	WindowStartsAt time.Time `json:"window_starts_at"`
}

// RentalReceiptActorKind Who triggered the cancellation (F4). Empty when no cancellation.
type RentalReceiptActorKind string

// RentalReceiptDepositState F4 deposit state in the receipt: released (default), captured
// (fully), partial (partially), held (still held; F5 will decide).
type RentalReceiptDepositState string

// RentalState defines model for RentalState.
type RentalState string

// SnapshotOperator defines model for SnapshotOperator.
type SnapshotOperator struct {
	HourlyRateCents int          `json:"hourly_rate_cents"`
	IsOwner         bool         `json:"is_owner"`
	MinHours        int          `json:"min_hours"`
	Mode            OperatorMode `json:"mode"`
	Name            *string      `json:"name,omitempty"`
	Phone           *string      `json:"phone,omitempty"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	// DisplayName Example: Ana
	DisplayName string `json:"display_name"`

	// Phone Example: +5511999999999
	Phone string `json:"phone"`
}

// UpdateListingRequest defines model for UpdateListingRequest.
type UpdateListingRequest struct {
	Category           *ListingCategory `json:"category,omitempty"`
	Delivery           *ListingDelivery `json:"delivery,omitempty"`
	DepositCents       *int             `json:"deposit_cents,omitempty"`
	Description        *string          `json:"description,omitempty"`
	HeavyLegalCession  *bool            `json:"heavy_legal_cession,omitempty"`
	MinLeadTimeHours   *int             `json:"min_lead_time_hours,omitempty"`
	Operator           *ListingOperator `json:"operator,omitempty"`
	Photos             *[]string        `json:"photos,omitempty"`
	PickupCity         *string          `json:"pickup_city,omitempty"`
	PickupNeighborhood *string          `json:"pickup_neighborhood,omitempty"`
	PriceAmountCents   *int             `json:"price_amount_cents,omitempty"`
	PriceUnit          *PriceUnit       `json:"price_unit,omitempty"`
	Rules              *ListingRules    `json:"rules,omitempty"`
	Title              *string          `json:"title,omitempty"`
}

// UpdateOwnerOnboardingRequest defines model for UpdateOwnerOnboardingRequest.
type UpdateOwnerOnboardingRequest struct {
	AcceptTerms  *bool   `json:"accept_terms,omitempty"`
	PayoutKind   *string `json:"payout_kind,omitempty"`
	PayoutLast4  *string `json:"payout_last4,omitempty"`
	TermsVersion *string `json:"terms_version,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// SearchCatalogParams defines parameters for SearchCatalog.
type SearchCatalogParams struct {
	Category      *ListingCategory    `form:"category,omitempty" json:"category,omitempty"`
	City          *string             `form:"city,omitempty" json:"city,omitempty"`
	From          *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To            *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
	OperatorMode  *OperatorMode       `form:"operator_mode,omitempty" json:"operator_mode,omitempty"`
	Size          *ListingSize        `form:"size,omitempty" json:"size,omitempty"`
	MinPriceCents *int                `form:"min_price_cents,omitempty" json:"min_price_cents,omitempty"`
	MaxPriceCents *int                `form:"max_price_cents,omitempty" json:"max_price_cents,omitempty"`
	Page          *int                `form:"page,omitempty" json:"page,omitempty"`
}

// GetPublicCalendarParams defines parameters for GetPublicCalendar.
type GetPublicCalendarParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// PaymentWebhookParams defines parameters for PaymentWebhook.
type PaymentWebhookParams struct {
	StripeSignature *string `json:"Stripe-Signature,omitempty"`
}

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// DeactivateAccountJSONRequestBody defines body for DeactivateAccount for application/json ContentType.
type DeactivateAccountJSONRequestBody = DeactivateAccountRequest

// CreateListingDraftJSONRequestBody defines body for CreateListingDraft for application/json ContentType.
type CreateListingDraftJSONRequestBody = CreateListingRequest

// UpdateListingJSONRequestBody defines body for UpdateListing for application/json ContentType.
type UpdateListingJSONRequestBody = UpdateListingRequest

// AddBlockJSONRequestBody defines body for AddBlock for application/json ContentType.
type AddBlockJSONRequestBody = AddBlockRequest

// UpdateOwnerOnboardingJSONRequestBody defines body for UpdateOwnerOnboarding for application/json ContentType.
type UpdateOwnerOnboardingJSONRequestBody = UpdateOwnerOnboardingRequest

// PaymentWebhookJSONRequestBody defines body for PaymentWebhook for application/json ContentType.
type PaymentWebhookJSONRequestBody = PaymentWebhookEvent

// CreateRentalJSONRequestBody defines body for CreateRental for application/json ContentType.
type CreateRentalJSONRequestBody = CreateRentalRequest

// CreateRentalCancellationJSONRequestBody defines body for CreateRentalCancellation for application/json ContentType.
type CreateRentalCancellationJSONRequestBody = CreateRentalCancellationRequest

// DeclineRentalJSONRequestBody defines body for DeclineRental for application/json ContentType.
type DeclineRentalJSONRequestBody = DeclineRentalRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAccount Current account
	// (GET /account)
	GetAccount(c *gin.Context)
	// UpdateAccount Update visible name and phone
	// (PATCH /account)
	UpdateAccount(c *gin.Context)
	// DeactivateAccount Deactivate own account
	// (POST /account/deactivate)
	DeactivateAccount(c *gin.Context)
	// StartGoogleAuth Start Google sign-in
	// (GET /auth/google)
	StartGoogleAuth(c *gin.Context)
	// GoogleCallback Google OAuth callback
	// (GET /auth/google/callback)
	GoogleCallback(c *gin.Context)
	// Logout End the current session
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// ListCategories Listing categories (config)
	// (GET /catalog/categories)
	ListCategories(c *gin.Context)
	// SearchCatalog Public search (no login required)
	// (GET /catalog/listings)
	SearchCatalog(c *gin.Context, params SearchCatalogParams)
	// GetPublicListing Public ficha (no login required)
	// (GET /catalog/listings/{id})
	GetPublicListing(c *gin.Context, id openapi_types.UUID)
	// GetPublicCalendar Public calendar (no login required)
	// (GET /catalog/listings/{id}/calendar)
	GetPublicCalendar(c *gin.Context, id openapi_types.UUID, params GetPublicCalendarParams)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(c *gin.Context)
	// ListMineListings List the caller's listings
	// (GET /listings)
	ListMineListings(c *gin.Context)
	// CreateListingDraft Create a draft listing
	// (POST /listings)
	CreateListingDraft(c *gin.Context)
	// GetMyListing Get one of the caller's listings (private)
	// (GET /listings/{id})
	GetMyListing(c *gin.Context, id openapi_types.UUID)
	// UpdateListing Update a draft or paused listing
	// (PATCH /listings/{id})
	UpdateListing(c *gin.Context, id openapi_types.UUID)
	// ListBlocks Owner view of availability blocks
	// (GET /listings/{id}/blocks)
	ListBlocks(c *gin.Context, id openapi_types.UUID)
	// AddBlock Add an availability block
	// (POST /listings/{id}/blocks)
	AddBlock(c *gin.Context, id openapi_types.UUID)
	// RemoveBlock Remove an availability block
	// (DELETE /listings/{id}/blocks/{blockId})
	RemoveBlock(c *gin.Context, id openapi_types.UUID, blockId openapi_types.UUID)
	// PauseListing Pause a published listing
	// (POST /listings/{id}/pause)
	PauseListing(c *gin.Context, id openapi_types.UUID)
	// PublishListing Publish (or unpause) a listing
	// (POST /listings/{id}/publish)
	PublishListing(c *gin.Context, id openapi_types.UUID)
	// GetOwnerOnboarding Owner onboarding state
	// (GET /owner/onboarding)
	GetOwnerOnboarding(c *gin.Context)
	// UpdateOwnerOnboarding Update payout details and/or accept terms
	// (PATCH /owner/onboarding)
	UpdateOwnerOnboarding(c *gin.Context)
	// PaymentWebhook PSP webhook (signature verified server-side)
	// (POST /payments/webhook)
	PaymentWebhook(c *gin.Context, params PaymentWebhookParams)
	// Readyz Readiness probe
	// (GET /readyz)
	Readyz(c *gin.Context)
	// ListMyRentals List the caller's rentals
	// (GET /rentals)
	ListMyRentals(c *gin.Context)
	// CreateRental Create a reservation intent (tenant)
	// (POST /rentals)
	CreateRental(c *gin.Context)
	// GetRental Get one rental
	// (GET /rentals/{id})
	GetRental(c *gin.Context, id openapi_types.UUID)
	// AcceptRental Accept the rental (owner)
	// (POST /rentals/{id}/accept)
	AcceptRental(c *gin.Context, id openapi_types.UUID)
	// AuthorizeRentalPayment Authorize payment (tenant)
	// (POST /rentals/{id}/authorize)
	AuthorizeRentalPayment(c *gin.Context, id openapi_types.UUID)
	// CancelRental Cancel the rental pre-acceptance (tenant)
	// (POST /rentals/{id}/cancel)
	CancelRental(c *gin.Context, id openapi_types.UUID)
	// GetRentalCancellation Get the cancellation record (immutable, both parties)
	// (GET /rentals/{id}/cancellations)
	GetRentalCancellation(c *gin.Context, id openapi_types.UUID)
	// CreateRentalCancellation Cancel a rental (tenant, owner, or platform)
	// (POST /rentals/{id}/cancellations)
	CreateRentalCancellation(c *gin.Context, id openapi_types.UUID)
	// DeclineRental Decline the rental (owner)
	// (POST /rentals/{id}/decline)
	DeclineRental(c *gin.Context, id openapi_types.UUID)
	// GetRentalReceipt Tenant receipt (immutable)
	// (GET /rentals/{id}/receipt)
	GetRentalReceipt(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccount(c)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAccount(c)
}

// DeactivateAccount operation middleware
func (siw *ServerInterfaceWrapper) DeactivateAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeactivateAccount(c)
}

// StartGoogleAuth operation middleware
func (siw *ServerInterfaceWrapper) StartGoogleAuth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartGoogleAuth(c)
}

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GoogleCallback(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCategories(c)
}

// SearchCatalog operation middleware
func (siw *ServerInterfaceWrapper) SearchCatalog(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchCatalogParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "city" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "city", c.Request.URL.Query(), &params.City, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter city: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "operator_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "operator_mode", c.Request.URL.Query(), &params.OperatorMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operator_mode: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", c.Request.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "min_price_cents" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_price_cents", c.Request.URL.Query(), &params.MinPriceCents, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter min_price_cents: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "max_price_cents" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_price_cents", c.Request.URL.Query(), &params.MaxPriceCents, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter max_price_cents: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchCatalog(c, params)
}

// GetPublicListing operation middleware
func (siw *ServerInterfaceWrapper) GetPublicListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicListing(c, id)
}

// GetPublicCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetPublicCalendar(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicCalendarParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicCalendar(c, id, params)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// ListMineListings operation middleware
func (siw *ServerInterfaceWrapper) ListMineListings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMineListings(c)
}

// CreateListingDraft operation middleware
func (siw *ServerInterfaceWrapper) CreateListingDraft(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateListingDraft(c)
}

// GetMyListing operation middleware
func (siw *ServerInterfaceWrapper) GetMyListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyListing(c, id)
}

// UpdateListing operation middleware
func (siw *ServerInterfaceWrapper) UpdateListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateListing(c, id)
}

// ListBlocks operation middleware
func (siw *ServerInterfaceWrapper) ListBlocks(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListBlocks(c, id)
}

// AddBlock operation middleware
func (siw *ServerInterfaceWrapper) AddBlock(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddBlock(c, id)
}

// RemoveBlock operation middleware
func (siw *ServerInterfaceWrapper) RemoveBlock(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "blockId" -------------
	var blockId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "blockId", c.Param("blockId"), &blockId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter blockId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveBlock(c, id, blockId)
}

// PauseListing operation middleware
func (siw *ServerInterfaceWrapper) PauseListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PauseListing(c, id)
}

// PublishListing operation middleware
func (siw *ServerInterfaceWrapper) PublishListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublishListing(c, id)
}

// GetOwnerOnboarding operation middleware
func (siw *ServerInterfaceWrapper) GetOwnerOnboarding(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOwnerOnboarding(c)
}

// UpdateOwnerOnboarding operation middleware
func (siw *ServerInterfaceWrapper) UpdateOwnerOnboarding(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOwnerOnboarding(c)
}

// PaymentWebhook operation middleware
func (siw *ServerInterfaceWrapper) PaymentWebhook(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PaymentWebhookParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Stripe-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Stripe-Signature")]; found {
		var StripeSignature string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Stripe-Signature, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Stripe-Signature", valueList[0], &StripeSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Stripe-Signature: %w", err), http.StatusBadRequest)
			return
		}

		params.StripeSignature = &StripeSignature

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PaymentWebhook(c, params)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Readyz(c)
}

// ListMyRentals operation middleware
func (siw *ServerInterfaceWrapper) ListMyRentals(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyRentals(c)
}

// CreateRental operation middleware
func (siw *ServerInterfaceWrapper) CreateRental(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRental(c)
}

// GetRental operation middleware
func (siw *ServerInterfaceWrapper) GetRental(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRental(c, id)
}

// AcceptRental operation middleware
func (siw *ServerInterfaceWrapper) AcceptRental(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptRental(c, id)
}

// AuthorizeRentalPayment operation middleware
func (siw *ServerInterfaceWrapper) AuthorizeRentalPayment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AuthorizeRentalPayment(c, id)
}

// CancelRental operation middleware
func (siw *ServerInterfaceWrapper) CancelRental(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelRental(c, id)
}

// GetRentalCancellation operation middleware
func (siw *ServerInterfaceWrapper) GetRentalCancellation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRentalCancellation(c, id)
}

// CreateRentalCancellation operation middleware
func (siw *ServerInterfaceWrapper) CreateRentalCancellation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRentalCancellation(c, id)
}

// DeclineRental operation middleware
func (siw *ServerInterfaceWrapper) DeclineRental(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeclineRental(c, id)
}

// GetRentalReceipt operation middleware
func (siw *ServerInterfaceWrapper) GetRentalReceipt(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRentalReceipt(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/readyz", wrapper.Readyz)
	router.GET(options.BaseURL+"/auth/google", wrapper.StartGoogleAuth)
	router.GET(options.BaseURL+"/auth/google/callback", wrapper.GoogleCallback)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/account", wrapper.GetAccount)
	router.PATCH(options.BaseURL+"/account", wrapper.UpdateAccount)
	router.POST(options.BaseURL+"/account/deactivate", wrapper.DeactivateAccount)
	router.GET(options.BaseURL+"/listings", wrapper.ListMineListings)
	router.POST(options.BaseURL+"/listings", wrapper.CreateListingDraft)
	router.GET(options.BaseURL+"/listings/:id", wrapper.GetMyListing)
	router.PATCH(options.BaseURL+"/listings/:id", wrapper.UpdateListing)
	router.POST(options.BaseURL+"/listings/:id/publish", wrapper.PublishListing)
	router.POST(options.BaseURL+"/listings/:id/pause", wrapper.PauseListing)
	router.GET(options.BaseURL+"/listings/:id/blocks", wrapper.ListBlocks)
	router.POST(options.BaseURL+"/listings/:id/blocks", wrapper.AddBlock)
	router.DELETE(options.BaseURL+"/listings/:id/blocks/:blockId", wrapper.RemoveBlock)
	router.GET(options.BaseURL+"/owner/onboarding", wrapper.GetOwnerOnboarding)
	router.PATCH(options.BaseURL+"/owner/onboarding", wrapper.UpdateOwnerOnboarding)
	router.GET(options.BaseURL+"/catalog/listings", wrapper.SearchCatalog)
	router.GET(options.BaseURL+"/catalog/listings/:id", wrapper.GetPublicListing)
	router.GET(options.BaseURL+"/catalog/listings/:id/calendar", wrapper.GetPublicCalendar)
	router.GET(options.BaseURL+"/catalog/categories", wrapper.ListCategories)
	router.GET(options.BaseURL+"/rentals", wrapper.ListMyRentals)
	router.POST(options.BaseURL+"/rentals", wrapper.CreateRental)
	router.GET(options.BaseURL+"/rentals/:id", wrapper.GetRental)
	router.POST(options.BaseURL+"/rentals/:id/authorize", wrapper.AuthorizeRentalPayment)
	router.POST(options.BaseURL+"/rentals/:id/accept", wrapper.AcceptRental)
	router.POST(options.BaseURL+"/rentals/:id/decline", wrapper.DeclineRental)
	router.POST(options.BaseURL+"/rentals/:id/cancel", wrapper.CancelRental)
	router.GET(options.BaseURL+"/rentals/:id/receipt", wrapper.GetRentalReceipt)
	router.GET(options.BaseURL+"/rentals/:id/cancellations", wrapper.GetRentalCancellation)
	router.POST(options.BaseURL+"/rentals/:id/cancellations", wrapper.CreateRentalCancellation)
	router.POST(options.BaseURL+"/payments/webhook", wrapper.PaymentWebhook)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1dbxtHtuBfKfTuYKlNi5RkBUhkDBaOHM8Y6yQeK555CA2q1H1IVtys6lRVS2YCAfu0wH2fPzAYXNyn",
	"ebpv99X/ZH7JxamP/qwWm5IoeTITIDBF1uep831OnfolSsQqFxy4VtHJL5EElQuuwPzxFU3fwE8FKI1/",
	"JYJr4OYjzfOMJVQzwSc/KsHxO5UsYUXx0/+UMI9Oov8xqYae2F/V5GsphYyur6/jKAWVSJbjINEJzkWk",
	"m+w6jk4Fn2cseYCJ/UzkiuklSQopgWsiQYlCJkCUphpwRS+EvGBpCnz3S3pW6CVwjaNCSi4KTbjQhGaZ",
	"uIIU1/Kt0C9EwdPdL+WNhwOuYG7mvI6jt5wWeikk+xkeYA3fMKUYXxAhScHfc3HFiQKl8EezllyKBJSi",
	"FxnsfjFnsKJ4NOSSZiw1Q5M5ZRkezHXsRjfU8yxJRGHXkUuRg9TMklVCc3rBMub/vmkdbpDTehdcE1N5",
	"RtczTldmz3qdQ3QSKS0ZX2ADZs6lhVZ2LMJSMnr79uXzvSjudsyXgoeHREoozIKBF6vo5IeIcVxxBhqi",
	"OKKJZpf4IQXzEXE3iqOLTCTvIY3edea6jiMkeCYRh37AFZdztDboVxU3QVcNKS5+hMTwjRC8OgeQFxcZ",
	"U8sAhLIrulZkTjMFhHHy4pCMxBUHSQS/EFSmiIZMkRdHNdhdCJEBNbgoQYG8hO7A38sCyNUSOMmlmLMM",
	"cBQPPEJ5Sqg/HEVKSLYnaEHMzxaXGwpCJE2/wjOocfImNICnakbND3MhV/gpSqmGfc1WEEIRCdTR0op+",
	"eAV8oZfRydHxQRzEGam3Gb21xap/XK4zuMlLyjJ74muz2wDVSUCU3GqnW4OGpY22RcHSULOMKc34Yjaw",
	"eQXwJla9kAD7Gj5oYpB0X7EUiG08jnZwGmZ1tbXHwfMp1xvXYR46tVOqYSHkGkUwW4QYpf19E5N8ZZfk",
	"hzMMEnKhmJ6tGJ8lXrlZMc5WyLoqVGVcwwKkgQ77GQbOdIZN29ApV+uGCi0iCAUDJDdyL5XeCRYZu4TB",
	"XZ/75jUwDgRhAz0b7OH44OAgxt7+i8OjAIIugV6uZxksaDZLnIg/+aXDB81AswxoOkO8nS1FIQesDsFJ",
	"tZAD4fCdb26lohZmCqZhpYLy0X1BpaQGdjlL3hf5LGF63QLGFy1QhMSw7cyBLZYXQi6FSAODdLtJlsCM",
	"rlCUBA7tMAQW26fgTG8CzGts+RYbIuoXGaiBoHxj2iKMmM6gtZHDoyY4jjexITtIE9viOvnVIR8GZWPX",
	"QbC1cT+MczWk6iftN8A1zU4pTyDLjMbYS+U00ULO3jOe1vUsDZxyXKdh87jejGrk3+H56+hgNGMhZ7YZ",
	"E3wW0gy/Mx9oRl6fvbZSpGyP2qJeUk20ZIsFSMA/YcqT2nbISMK84GlMkiWVC7igyfu9MfkT6jt6Cd6u",
	"Q4UH1JTPpVgRSq7gYinEe7KkPM1AxkQvmUL9B7vAJRhN9SlhKaxyoYHrKbdTITRnLI1JBa2YhLe6N57y",
	"O6kwLdSrZtx43venb22pLXiMmGmQKzWjSQK5tnZal5FurRLEEdrJszov3aCmDlAYmkP2byEE8+elueF0",
	"/34RimqGXOFH+EBR945OtCxgo6LtO4anTzLGN515hW+epkWhkdBmyCnTwvAzFC2zglOry5qv7P5XTK2o",
	"TpYIGb0EGTamOkuzNmwADCk0YBAVdXM+cOIrUIouAmbNK5HQDHuRZbGinPiG/WPM3sO6OTlOPb55BZ3j",
	"SCEqR4yaY4fO6PdAM71841xbXYigGcWSFlASyjUwKXoUaW8Kl+3F+yHWDHYLLdEJynvV+25j8Xw6uuJQ",
	"5bDtr7LgJkjYZC4kOTf9zokHpDPDrcUM6ThoyA9ktQ+thhr5P3OugqHyIKC7NmH2ckUXQN6+eYUeNqUF",
	"gs9iJnkP63HPxl/awQ63VXwfSNU9eGxVd2tz0rKVwX28X7pXpe5ArMjTLflByP7v4KBfd3w/innJge5P",
	"R3cU4A9yg9Le5qQ1ob2ivKBZFEeQQaIlS4w/ZLHUs0RwpWWRuD3ThWRJkelCmuaGBQU19DYfDUjrS5BB",
	"4Vt5fzzICJVAnxIu+D6scu1YHXBUJtJx2MFlfhugxfmWcbWiG4D3XY3HNfeDZ5KtZ5JqGEq1LAWuHTO5",
	"iTL8pC99e8ehu3w5aAevnF40ZIpvsG0bRGaAG4Dy2h1jEyAlUy4/3MiXUG4lbsCg18FNEmB+qCJ5rtT9",
	"WQtNs9BPrV3mVueqRvNdY7eDGyDwxjPSJghSkRQr4HpWzROyVeBDDpIBT2BDQzx0B4YV/eCO/In1MtyA",
	"Z1rSS8hmEpA+Et1LFn27O3Ow9dzCcIYh1H/Gaa6WQu/EAzqQyHaqyvgNdnWZoTpMU6V4TGWglLc3y8py",
	"e5VYrAvCrSXbEJF15vUHj4GppHNdxYcM+85poYLxuDjqMNAus1Izs7GbIlzovvGr9e4c5wOwcYqwyt0b",
	"yuyLSLYA3ooUlisNwavBxmvw4ravcO6wqDZDEF44wXdlZLALrpyuRaFLf17b6UZ/KoDYNgTbkBGMF2OS",
	"sw8xuaD8/V5QZrtBM6r0cRhgtoECHWaPQ/xCzTZbmZC26yXIlvu+59xqq+0srT1Y6Cxf0zXKjpdl0L/l",
	"Ud2KJ1CtUXParCzczrbeiiOjuEMpNDPidWgvzEUoJMy8l6ezCt+g5tS5bRizdM0ma+/XCbmgL1kKsk5m",
	"+GuOIOJC5H2Oa9NrltvTdXJCd/24zhk8aL3dDAaHiIhyXnOv+6FcYkccWf92Dxu4H7uq2koNaF0YVzga",
	"RxtERhCB4pu8UI6W/mQ9819fBikqpZrelc6qOMGsL7h9BpoInq2J4LWwgg0MqPE90JdvXlrdLfPqmLgW",
	"dk7y9//3Z7sgBdp4ltzP4/+NCRxTbnEEGZnOIJ1010xK59RcyClvjK6eErbg1vWilyCvmAIbu6hQNQOq",
	"rAVGc11IJ82lZjQL4uW9sIKSAA1/HZ6xMJwuO1ktFR00kCqEsD1swX5RkbnbxLhB3P7Lksj9FyWxt7/y",
	"Z1v7oYbITiTUfiwRsn5ezZ9qp9r+yR1t1XtYCpVpElsqDdJ4qczWAIT6vukUtlOs1XlKM+ApDRj1Jsmr",
	"acTeMeb1UIlDbfN5y1hbj9W0wYRuRMTCLisH0eABNlwAn0rAYHaDKynAmjfGA26rkww8kVqMMeiRuqH9",
	"9n6ie8kfGeo3H2gb/8M5xwfa3Q2Lu9cR7RxXn5w/emPK3Bug6bo/krmDSG1LK9NI5YQdfsGJVUerCKjE",
	"tY1DcdD4TiHWUgGi6doYDXpmP78bGHDdJlZsA/mhzBy0SSk6H1OgacY4bMUnE7FaMRO0HKwj26yDLfnx",
	"7Xi4yWGoqeJ9TXZr8O4o29aprn0W6pYi3zdXNaftEDbmm9dFyUDAlO2dr2TbbkMcPtZfud0EEoZbfLdI",
	"NBoUDrX0WkVDTarctiHy7S347dOgusnT3bVWodS75Uk1cL5xTh3k68qsDqcKIkcfVgYIpMGUGsDuZ8D1",
	"bMm+NMktD/mecyvrCZCzOcC2bgdn1m3brWUVbtvd2ZvDQ6/DOKxSxZbkE8SeGZ1rkLOkdfjddXURcnDX",
	"/pzYO3oXJaCbmmY3erRchIQpUl+pufVT93L5sca9fHHmTrSpId3kIoqjJWRhD6bjRM7LcYONcMV4Kq5m",
	"5l4dBGIamA1JEaiXQF4cE9ucoAOKjBQA8WmSCbBcj5ujhaIdmxylHUbQIPPOetuw66XiMEiG4t0W2N3H",
	"D/oodhMjqNNiP3f9QyE0fFcEc2RL5n+xBZ/YXrvdUjd8KJVpx1rQdhxli8DPDU7U7aR/M1YQRoe76gj9",
	"iOk4w6aLEU2m86elaN5OaPLW0YvjvTH5ukqI4qLRYFxzsu9AG+hEFRqLmwOQ0eHBb4iYE3PxnNkA+rQ4",
	"OHgCvz06XjomarjjBiKsr+EWIrmX9ofR+72rOgNGflhtaHjEyLTwZyktUp8QL5/JKIU5LTK9FxMvqKd8",
	"NC+ybL0XE7cpMnIfzJcou8lIaZZl5vNT8uJzcoV/pZCwFPa2iRbdoArcAm92YhFvwdIHNu3RENtJGban",
	"T8sY6SWT6T4Cbl1mtTwlP4MUlpn4735rOEZdh9koVu6g1rYWjd38ijloZCYVhZJRtVrDYgyeER/l6lny",
	"0Ktj4RtjgQthcUkcDiHD2S1NaXpnCXord0CPOtzc+LegifX+lqAkWhiCt/2JOTrD4T+rHUcY3C1Rv73m",
	"bZhPpXw3NG+TVTR12xrnEpynYBrFU15+v4DZ0fFyGsVV00x3vrL4aNwTrrvN6cJRrQPdNrffNlp7FlX6",
	"fxsTh30sZtNbOwZdv7sGEetaVMhZ8+lpVkHvSwcaHcAOsxo66YU5cJP31sqaKR3XUeU3NueeMyuGHDer",
	"f3YMhs9yKRYSlNqUdNNJKb2XTPNaemM4rXhgYuxtYoR3TYBc2Wtx3W3XV74hMfJtng64SNmuPlNR9DNO",
	"o7h+E2XIVXe/vWqYzz7//PDwS/9fc8QnRxtGbIElWEmmf+//qsPwz1WH4V+VFzZUXuihk1bu8w0VDVDT",
	"sAGKMA61kqS3z3cekHDc2oQJSCeFZHp9hvDyvi/xngEWX8O/GI9O3FeRZ85lxHrmC5BV6Jaz/wtrWzGM",
	"8bmwA3JNbQ071/+0ingXMotOoqXWuTqZTPzA4wsJXPBxkoki7ZBy9OKQnOKgJ8ReikppCuR3QiwyiEkO",
	"cs4ysvr4N85WIiaZWKBBACQFhVoh/fgfH/8qxlP+4oicUv3xL9jgxF6FTaiMyUWhEkryj/9lvoitSp8K",
	"6TXLVMRY+AGzwD7+RTJBUiDIXgVnWHrJLAbInCXLahSc7gl5Y0pV0ROSSEYlsdGpmNBCo9ZA0XhZ0BVw",
	"LcjozGQH78W+QEQ85TQBpqmcSEgKha0hEwTxTDLQfilcS0FSSn6kHDKKazs8WsaYl5mwC0HYqtAf/3IJ",
	"GUkFyURCbUdc3zGx4Sa3gs9Ixn4qWGrhdUJykX38m2YJrWnYlORCEmMpwpS7KUfVsOTv//bvR8fLifHj",
	"JPgp//ifap/xj39LmIibi48Jupmo0VD34ilXecY0gRV5QhLKPjC+pIqMaFYsCsgmSyGpmiS0MMvbQ9MC",
	"/2dKffyrIIdHv5lymgOniihxIYG4fp+ZfjHpgoMhhq0Yt+froF6ruwEkERcSNUZn6dRyWyfNLNZ4yi8y",
	"8VMBFjkMATThjduqG4WY50YUSIbpKWZBvraIO42///8/E79Za0BkLAGX/eLI6puX39d4XEll5Nnrl1Ec",
	"lZwhOhh/Pj5wIojTnEUn0ZPxwfiJcY3opeECE1rV7VvYKxTtK+a6kFw5R2OWgfTF28bkW4zbEMaTrEhB",
	"OcokqjB8J55yWFGWxXjP2mT5OiqeM5CKXMBacOu/tCTpa8XZXZf29cs0Ool+B9ppaUZRrhXtPDo4uLcq",
	"iH6KUNlMVyjTQ+s6jo4PDvsGLFc4aZSOrDPi6OSHJgv+4d31uzhSxWpF5TowYxxpulC2Kov95p2RFjoJ",
	"VPaz7l9EFwS+UQIx6CbhR5MiPyanthgfXlK6EHpJVvQ9KFvqxg1PIGMLhtlPGgkBGRqQ0Ysne2Py2t6v",
	"ws5KYwVBV/WQjF4c7YWOr6Fnu2tGoPRXIl3f2+EFdfnrpnqsZQHXj4NAdnnpHREIOz3Z3Kkq3oo9jo6G",
	"TFMvK7oVotqdkUumDLYYpMMSj/5qWhdtr+OS7Uyq8plGmRIqwIJeShsgNuMzTi4Px8QpfIpkQC9LFqKA",
	"ymSJeEgYv6SSUa4RI1/yfW9pE+vmUIRKW+a1NM8Ru5vd3A0GRZyN/1tEoBCCd6ry7AjJe6v/fDqIXi3x",
	"HpB9x6hbrRWvat7Iag3OFno5WRghd4O4TJmERCtkm1Ygjsl3eI/G/kFschAmQFwelpIUMVSDlEWOYBPS",
	"aB4YOklwj1yXvTgwI0k9k+ZC+urAIbw801RqO7GBQAslnhwc9e+g2oC91J2CtXYxt9ab2hW2tI0QBNjn",
	"B0/uDeN6KxT727vE3yJDQWfo2pTZNKGg6+v6qRuglMoKW/B9xutnjoDqHPgEdR/U4XpP/usPyZLyhT1a",
	"rJZcnrhIIS5P0ByuyMGpVO4gUQ0GjV3daRKLt7FhpbKOVNjrCi4IzfPxlP+hALnGGBpdKXKOU53H5NwE",
	"5M5t53NA0J0bfieBpsQUpMNR3r55NZ7y75dAFDLtpvpGuFHuKnRVkIiqcu94yp+RtEvrVs3A/UFKbPyu",
	"1iqo25lpTz14t0XRGjhuh6cN3HAw+A6phSTVmvqQwxqd/aLra54qQhsFztFFoNSYPBdgEbWCTx0jphwP",
	"L/WNlhh0ct5uFQLjK7uSDtM/DmVmWRQDnjo+u1tV9mun5/tq8zVvQhesCdU0E4uJ8zw6v8oA08R0M7HA",
	"smfsbBPUVLGRt96cn2rKc5C++ZqMjB9rj8javUXvLtA9DBbVkNNqpXcUuYNqorTKCHdcgAHjpVpgE9ud",
	"ElWDGBlZtrlXOxwH2tb5eFzsPZ0zq4uVxRgq7CVnRZ4LqRWZs0wbY3BdHkNM0HUZT3lqcwo0elIyDLHi",
	"YeNq/TiGLrzpQRMplEUFJDUJU+777sVVgYaV4cXGE0kkcmvDIvF+DBmZAibIn40/GPU/LGFjFcXDfcZT",
	"+ACpfTeBkjnDP3IsJYa9g8LXAODUQc+kI9AVaMOefnAet58Ke9emdLhVd3YGicWO3/067hnZXvrpZ4Q9",
	"/VBYNPo1AotRPHQcLe5jlOattKFAapcxCo/tLkltBXdfGTs84soE+NDpXV5GLwe/ObutZzz64V7Hc7WN",
	"qkFcno7x39/ky79+d0dGNwC0SHshZobfI5d3Fl/Jhpqc7XXTHuTok1swXvL24fxt8gtLrweJILci6xBG",
	"2UG7zG9MjL9X2dIwU+6LfRk2VHIp/+3EudSf2pv4tUncD1M+ZyZTKmcf8IJabK3uPee6RVuC17qV2ddL",
	"4x2Y8oJrlpEXT3p8bs27tzs88+ZEoVOvwdZqLMebNZby3ZggbthzGooaYfaNbtSKnlyWRN0ID/K8nsIA",
	"73rRb5LU7qJvxEPsihTSEKDNwkRMkVrl3XjK86ywLRzZO4+fRRgMeRLNVjgaMVHPmvaKrhmaTfnVsnQT",
	"poTydTnzjbhVXrIfJB4fSRi92znml2DoR/0SBe4H+/1wnxwBLE314p83YvrRwUFVgOv333//2tdEN7dL",
	"MJdgPOUlliZLSN4TNOaM19pezw3aUb938+/wzFsFmkNPYuH6O8r6JXDcXy7FRd2xKnLlZNdGndwDD0z9",
	"zHqZshR1cGN+to1V556QsKAyzXABYm4zfsfkrXJmEva0TwelVC1NmLzPXPqGcZ928jAGU2/5yC7cS69y",
	"AyQ27PUAhjJOX5vxf6lKvamOu/zK0GTQ63BaOm1Khs/JuSmPdz4mz/Hfyv/tHffMlYlOptyqTWPyfXmq",
	"q0Jpoqhmar72Wg1ZmElGJkulzHedcidCYuJyaao4suCWZI2BFbf1nbk75ylvpBpbj5LlKbHzrJUlYH11",
	"Vjuu/3rKmSpVoNinCqegKcuUVbXMrkwqxR65gLmQUBeQJihLVuLSRL/OSzUOodf1eZnbbYbLGLhPuT+i",
	"p1ULNBtFUUG7GSbBAUgOUiEC0Ck3R2WewnMje5AzHSKrxps6z10VxF3EH4KP9wyKPRzet30QjD0YsPnK",
	"RL+eEJsFO6HE4kVWKuQBnlCXA8NtF88njHcDM+ZLbq5pzYnmabJluDhrhIyMmVKoinW6awJhFfCb9QOY",
	"FjegS00wPBSibK+4DcWR35kCcsY0DkoQMsqlYVt7vbJk5/pdb76CjSGXiyXGqlXkaskyqMkudM6d24qu",
	"52PyrDKvS5br+eUFEEiZNhfkpCgWS3sLGXiaC8b1U6Ibom3KzaiEaTJnUunY9CZM4zM91fsJhC4o4/0Z",
	"DnV03lWGw22Y74NQk89wyD51qsIOX+4+MPmqsrVLPH1KSjxzSgfimYfWwyRqeClibn0VqnZiw+TJpCp/",
	"N8DGoLWnKq2z3svnhohwpsTFesoDpgQqYSvKUc9zvM3Yrn0Wxld2gQ9hW3Rf4hxgZbj1/SrEjr2Md8ng",
	"CiVP97TVo0qboHX0LMWYrENGF0GuxIdDLWIPyRo+KFHQ0MhoPuWjOgr6it+KcRM7t69HtyDxlLx4Yi6v",
	"TvlScFFIK4zKVCN00tb8bUF1yb9ruyPZ0n4294F1+gAZ9ZDNY2j3n6R4sdBwWIlGLYEPDokvPCPatUR5",
	"lqKrN0D124mSyS/m35fWVknBPLEdkCtoj1eUGxYjr6lyQWHr4XiPFz+5d1HRAtW6TCxCJGYnqKhsUxqF",
	"PQFpeqW/Dm5uQbDNmT4AI4+DgzqUubvDuYmRRiWyjxk8lnx6jUtQ4ejhS5dgZXDOZnI1Ul+nHJ1G1mpH",
	"T7ELyPiONt0I6SvonjUzfxI2uVNN/2VEVEZEzQ24rV/ZnGsIoYbyadfxceniG8f+e8wXwnjbV/ssy/ye",
	"p9x6q1EmwCXNCiM7DHXYl+TRn+BHMi8Az52zeG383FNurzowTphWVSqbqXxiczSt2XN8dGS9aDaaqlTp",
	"z5jyRKSgUEYVyh1qLbHd5EBlmZ2/5qvodzq4exifCMGWuDUSkhTWoZLufdIUvGP1yJ1PHSB7VUymn/aM",
	"KjMRjZd2bjS1r5ZgssIr0xmv0CnQodCHL5tZt7RNIGRMvjJXgdDiuQD7pGgtNGJbmkCFJ6lyLz0O3vaL",
	"QTvE0PZUAUw1TUgFVku8DxDW65m4V5+60UVqjsHVoKlGRIk/JmegDS2e168hm0sr5+ZiqJBpmXXuyjub",
	"vA6l6So3yGEV5zJjyNCzS1UygxF3uxCZWBOzJPjHVKkiwj72ZHk6Ms0pvzwkIzu1Lmhm06AAr/dySLRJ",
	"Flm4EGFGMWmacYKXzXp9rSHc2pXPtef29wP7Xm+D4q767Cd7A8f5JLtsaiKkw1LLnPq5pXtIRE3cVd56",
	"Mn5bva2/99OTcmRvEFTajEXU/TO24FQXEm5Mon23GywMPVQ0HPlaNxIu3a1SIwQsYhxsPuOvaFqi/a0Z",
	"ZiUZz177++5kpDxokbmwOWvqZfVwlT9qd/KmLP4WmULt9J8SwSSdz1liLvzZLp8fPKk9TESMeo5Imgma",
	"Wl63AA6SJSZ96vnZt5PXL18is6oeHjh3pffPyVxkmbhS5JmZbf8V5YsCXdkj4DHJ9f5Xb2ICCns/t/m3",
	"5v54Zm7smp/Dzgqz9x2ym+bbCwFmYxpE93zPa+Os35qcQzPzddN1QVO2IT/KXf2sYUwgPWn9xrV6iPiB",
	"nWtI0MCv6jGykGQJEQ9T/01/DtIfMVHHaCw4VC7N7TGGPyoy8iXjMJMG4tLuKnWOeMq5qJzszstZyxiy",
	"yojnYr7an8tfdBc8lNVw7VJtro3NsEEj8txV8zp3v4/Jy7IChEuannK3znKBsa9OSnSRhysV2FQNd6y7",
	"TMLxFWQfxV/fqqvci65Nb/1DiJnbGY5fbu6B160yluiH0IrKfJ96FratIuNpZy9IjDUm18796RhnNRzd",
	"mQSxzK0PO35diTfSwzPIIx8kd7p+9BPLHB/aZdeKWpo1PD6mkapI46fvUR7Kh7aK1DlNt5KHI5uaN4iN",
	"TEpQPDI6+WXYU3Vm0U4vJjWeWw5eR2s0+NUg1wMEjz0EiDPrthNtE1u35XER0hZS+xT4W1lj9p+Tv9mD",
	"qPO3XMJ+zc15G9yyZXqH1h+oehDraiWCJ1aJMwu6oqo6pvGU/9HdBGhV0Xa1Eup3c+SY+KmOD47d9YjW",
	"sw42+0ORNWh7b8OtgSnCVqvCvGN4ghEoKSGpHuHhcOXee5YwBwk88bUShGQLxnuv7wXerdo5/jdmC9Y5",
	"qP/+a9Et+7BrVJ5rbGu4mecOQDWv79Xx+JHT7vD0nTug/S5ILjKWrMno2en+4Xj87HT/iz2LxdYFMeVl",
	"UKqklLhLJqbSICX+EZPSW+CK3CQZVaq8ZWTzciVk60YleXz2PAXJfHrFlI/MYyyxCZTsa7FvK+bGxBQY",
	"h/T/xN1723tmGPNMuuVIqsjMMm2py97alvYuha+IPuWjw6PfGOeH4SGf+XmqtwVodoVBaVHoPbMf698w",
	"MRisH1ORfhCDPvNvdTgAOUZl06wwlt5XrfzcsylOtJjy85KtnSOflSvkG3t1j8pJVT8IT7QMkE+5qTx0",
	"Xr13c14G0hFyZUqbx/njgy8Jm095o0fK5nOQam+TP6bDrXbrm6lP90gho+35ZuVTG1UlUYkELCpugvn3",
	"70baann/IA6lf3Tl3OlTpfJSekIrRuvZ7E3ypqNYuQcSHldrf24XsVMnbWOOGvVfP6aVUD5P8c9pJLgz",
	"ubUXRFbPtd3sVPXvuu38rP1EwSN3P/0a9ODvrXHkDqCm+u49nr/VPfPupwg8QN8oe38ymZiw7lIoffLF",
	"wRcH0fW7cu2d7q7WQ0ykD2vWi2Cp6Dpud3GVCxv3cqtCe64rHnGg72tbedv0KasRNjuWlVzDr3Gdvnn7",
	"3BSCqK6bvjjaq/r7r0OT2/zllClzmX8dV3E/XI8r09MYzVcl6Q5WIkoZN1EuO9NgjjIVrKuBZBlU/SXs",
	"1yOeKFz1Ap+z0BilTEvoDnMasHLKgvvle431ndUF6PW76/8eAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
