// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountStatus.
const (
	Active      AccountStatus = "active"
	Deactivated AccountStatus = "deactivated"
	Incomplete  AccountStatus = "incomplete"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Deactivated:
		return true
	case Incomplete:
		return true
	default:
		return false
	}
}

// Defines values for ListingCategory.
const (
	ListingCategoryAgricultural      ListingCategory = "agricultural"
	ListingCategoryElectric          ListingCategory = "electric"
	ListingCategoryHeavy             ListingCategory = "heavy"
	ListingCategoryLightConstruction ListingCategory = "light_construction"
	ListingCategoryManual            ListingCategory = "manual"
)

// Valid indicates whether the value is a known member of the ListingCategory enum.
func (e ListingCategory) Valid() bool {
	switch e {
	case ListingCategoryAgricultural:
		return true
	case ListingCategoryElectric:
		return true
	case ListingCategoryHeavy:
		return true
	case ListingCategoryLightConstruction:
		return true
	case ListingCategoryManual:
		return true
	default:
		return false
	}
}

// Defines values for ListingSize.
const (
	ListingSizeHeavy ListingSize = "heavy"
	ListingSizeLight ListingSize = "light"
)

// Valid indicates whether the value is a known member of the ListingSize enum.
func (e ListingSize) Valid() bool {
	switch e {
	case ListingSizeHeavy:
		return true
	case ListingSizeLight:
		return true
	default:
		return false
	}
}

// Defines values for ListingState.
const (
	Draft     ListingState = "draft"
	Paused    ListingState = "paused"
	Published ListingState = "published"
)

// Valid indicates whether the value is a known member of the ListingState enum.
func (e ListingState) Valid() bool {
	switch e {
	case Draft:
		return true
	case Paused:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for OperatorMode.
const (
	None     OperatorMode = "none"
	Optional OperatorMode = "optional"
	Required OperatorMode = "required"
)

// Valid indicates whether the value is a known member of the OperatorMode enum.
func (e OperatorMode) Valid() bool {
	switch e {
	case None:
		return true
	case Optional:
		return true
	case Required:
		return true
	default:
		return false
	}
}

// Defines values for PriceUnit.
const (
	Day  PriceUnit = "day"
	Hour PriceUnit = "hour"
)

// Valid indicates whether the value is a known member of the PriceUnit enum.
func (e PriceUnit) Valid() bool {
	switch e {
	case Day:
		return true
	case Hour:
		return true
	default:
		return false
	}
}

// Defines values for ReadyResponseStatus.
const (
	NotReady ReadyResponseStatus = "not_ready"
	Ready    ReadyResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyResponseStatus enum.
func (e ReadyResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Capabilities AccountCapabilities `json:"capabilities"`
	DisplayName  string              `json:"display_name"`

	// Id Account id (UUID)
	Id     string        `json:"id"`
	Phone  string        `json:"phone"`
	Status AccountStatus `json:"status"`
}

// AccountStatus defines model for Account.Status.
type AccountStatus string

// AccountCapabilities defines model for AccountCapabilities.
type AccountCapabilities struct {
	// Publish Always false in F1 (owner onboarding is F2)
	Publish bool `json:"publish"`

	// Reserve True when profile is complete and account is active
	Reserve bool `json:"reserve"`
}

// AddBlockRequest defines model for AddBlockRequest.
type AddBlockRequest struct {
	EndsAt   time.Time `json:"ends_at"`
	Reason   *string   `json:"reason,omitempty"`
	StartsAt time.Time `json:"starts_at"`
}

// AvailabilityBlock defines model for AvailabilityBlock.
type AvailabilityBlock struct {
	CreatedAt time.Time          `json:"created_at"`
	EndsAt    time.Time          `json:"ends_at"`
	Id        openapi_types.UUID `json:"id"`
	ListingId openapi_types.UUID `json:"listing_id"`

	// Reason Free-text owner-side reason.
	Reason   string    `json:"reason"`
	StartsAt time.Time `json:"starts_at"`
}

// CategoryConfig defines model for CategoryConfig.
type CategoryConfig struct {
	Category        ListingCategory `json:"category"`
	DepositMinCents int             `json:"deposit_min_cents"`
	Size            ListingSize     `json:"size"`
}

// CreateListingRequest defines model for CreateListingRequest.
type CreateListingRequest struct {
	Category           ListingCategory  `json:"category"`
	Delivery           *ListingDelivery `json:"delivery,omitempty"`
	DepositCents       int              `json:"deposit_cents"`
	Description        string           `json:"description"`
	HeavyLegalCession  *bool            `json:"heavy_legal_cession,omitempty"`
	MinLeadTimeHours   int              `json:"min_lead_time_hours"`
	Operator           ListingOperator  `json:"operator"`
	Photos             *[]string        `json:"photos,omitempty"`
	PickupCity         string           `json:"pickup_city"`
	PickupNeighborhood string           `json:"pickup_neighborhood"`
	PriceAmountCents   int              `json:"price_amount_cents"`
	PriceUnit          PriceUnit        `json:"price_unit"`
	Rules              *ListingRules    `json:"rules,omitempty"`
	Title              string           `json:"title"`
}

// DeactivateAccountRequest defines model for DeactivateAccountRequest.
type DeactivateAccountRequest struct {
	// Confirm Example: true
	Confirm bool `json:"confirm"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: unauthorized
	Code string `json:"code"`

	// Message Localized human message
	Message string `json:"message"`

	// MessageKey Example: auth.unauthorized
	MessageKey string `json:"message_key"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Example: canteiro
	Service *string `json:"service,omitempty"`

	// Status Example: ok
	Status string `json:"status"`
}

// Listing defines model for Listing.
type Listing struct {
	Category     ListingCategory `json:"category"`
	CreatedAt    *time.Time      `json:"created_at,omitempty"`
	Delivery     ListingDelivery `json:"delivery"`
	DepositCents int             `json:"deposit_cents"`
	Description  string          `json:"description"`

	// HeavyLegalCession Required true for `heavy` category when published.
	HeavyLegalCession  *bool              `json:"heavy_legal_cession,omitempty"`
	Id                 openapi_types.UUID `json:"id"`
	MinLeadTimeHours   int                `json:"min_lead_time_hours"`
	Operator           ListingOperator    `json:"operator"`
	OwnerAccountId     openapi_types.UUID `json:"owner_account_id"`
	Photos             []string           `json:"photos"`
	PickupCity         string             `json:"pickup_city"`
	PickupNeighborhood string             `json:"pickup_neighborhood"`
	PriceAmountCents   int                `json:"price_amount_cents"`
	PriceUnit          PriceUnit          `json:"price_unit"`
	Rules              ListingRules       `json:"rules"`
	Size               *ListingSize       `json:"size,omitempty"`
	State              ListingState       `json:"state"`
	Title              string             `json:"title"`
	UpdatedAt          *time.Time         `json:"updated_at,omitempty"`
}

// ListingCategory defines model for ListingCategory.
type ListingCategory string

// ListingDelivery defines model for ListingDelivery.
type ListingDelivery struct {
	// Coverage Free-text delivery area; non-empty when enabled.
	Coverage string `json:"coverage"`
	Enabled  bool   `json:"enabled"`
}

// ListingOperator defines model for ListingOperator.
type ListingOperator struct {
	HourlyRateCents *int              `json:"hourly_rate_cents,omitempty"`
	Identity        *OperatorIdentity `json:"identity,omitempty"`
	MinHours        *int              `json:"min_hours,omitempty"`
	Mode            OperatorMode      `json:"mode"`
}

// ListingPage defines model for ListingPage.
type ListingPage struct {
	Items    []PublicListing `json:"items"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
	Total    int             `json:"total"`
}

// ListingRules defines model for ListingRules.
type ListingRules struct {
	DocumentRequired   *bool `json:"document_required,omitempty"`
	ExperienceRequired *bool `json:"experience_required,omitempty"`
	MinAge             *int  `json:"min_age,omitempty"`
	TravelRestricted   *bool `json:"travel_restricted,omitempty"`
}

// ListingSize defines model for ListingSize.
type ListingSize string

// ListingState defines model for ListingState.
type ListingState string

// OperatorIdentity defines model for OperatorIdentity.
type OperatorIdentity struct {
	// IsOwner True when the operator is the listing owner.
	IsOwner bool   `json:"is_owner"`
	Name    string `json:"name"`
	Phone   string `json:"phone"`
}

// OperatorMode defines model for OperatorMode.
type OperatorMode string

// OwnerOnboarding defines model for OwnerOnboarding.
type OwnerOnboarding struct {
	// PayoutKind Opaque payout kind (e.g. pix, bank).
	PayoutKind      *string    `json:"payout_kind,omitempty"`
	PayoutLast4     *string    `json:"payout_last4,omitempty"`
	PayoutSet       bool       `json:"payout_set"`
	TermsAccepted   bool       `json:"terms_accepted"`
	TermsAcceptedAt *time.Time `json:"terms_accepted_at,omitempty"`
	TermsVersion    string     `json:"terms_version"`
}

// PriceUnit defines model for PriceUnit.
type PriceUnit string

// PublicCalendar defines model for PublicCalendar.
type PublicCalendar struct {
	Blocks []struct {
		EndsAt   time.Time `json:"ends_at"`
		StartsAt time.Time `json:"starts_at"`
	} `json:"blocks"`
	ListingId        openapi_types.UUID `json:"listing_id"`
	MinLeadTimeHours int                `json:"min_lead_time_hours"`
}

// PublicListing defines model for PublicListing.
type PublicListing struct {
	Category                ListingCategory    `json:"category"`
	CreatedAt               time.Time          `json:"created_at"`
	DeliveryEnabled         *bool              `json:"delivery_enabled,omitempty"`
	DepositCents            int                `json:"deposit_cents"`
	Description             string             `json:"description"`
	Id                      openapi_types.UUID `json:"id"`
	MinLeadTimeHours        int                `json:"min_lead_time_hours"`
	OperatorHourlyRateCents *int               `json:"operator_hourly_rate_cents,omitempty"`
	OperatorMode            *OperatorMode      `json:"operator_mode,omitempty"`
	Photos                  []string           `json:"photos"`
	PickupCity              string             `json:"pickup_city"`
	PickupNeighborhood      string             `json:"pickup_neighborhood"`
	PriceAmountCents        int                `json:"price_amount_cents"`
	PriceUnit               PriceUnit          `json:"price_unit"`
	Rules                   ListingRules       `json:"rules"`
	Size                    ListingSize        `json:"size"`
	Title                   string             `json:"title"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	// Message Localized human message
	Message string `json:"message"`

	// MessageKey Stable i18n key
	//
	// Example: ready.ok
	MessageKey string `json:"message_key"`

	// Service Example: canteiro
	Service *string             `json:"service,omitempty"`
	Status  ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	// DisplayName Example: Ana
	DisplayName string `json:"display_name"`

	// Phone Example: +5511999999999
	Phone string `json:"phone"`
}

// UpdateListingRequest defines model for UpdateListingRequest.
type UpdateListingRequest struct {
	Category           *ListingCategory `json:"category,omitempty"`
	Delivery           *ListingDelivery `json:"delivery,omitempty"`
	DepositCents       *int             `json:"deposit_cents,omitempty"`
	Description        *string          `json:"description,omitempty"`
	HeavyLegalCession  *bool            `json:"heavy_legal_cession,omitempty"`
	MinLeadTimeHours   *int             `json:"min_lead_time_hours,omitempty"`
	Operator           *ListingOperator `json:"operator,omitempty"`
	Photos             *[]string        `json:"photos,omitempty"`
	PickupCity         *string          `json:"pickup_city,omitempty"`
	PickupNeighborhood *string          `json:"pickup_neighborhood,omitempty"`
	PriceAmountCents   *int             `json:"price_amount_cents,omitempty"`
	PriceUnit          *PriceUnit       `json:"price_unit,omitempty"`
	Rules              *ListingRules    `json:"rules,omitempty"`
	Title              *string          `json:"title,omitempty"`
}

// UpdateOwnerOnboardingRequest defines model for UpdateOwnerOnboardingRequest.
type UpdateOwnerOnboardingRequest struct {
	AcceptTerms  *bool   `json:"accept_terms,omitempty"`
	PayoutKind   *string `json:"payout_kind,omitempty"`
	PayoutLast4  *string `json:"payout_last4,omitempty"`
	TermsVersion *string `json:"terms_version,omitempty"`
}

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// SearchCatalogParams defines parameters for SearchCatalog.
type SearchCatalogParams struct {
	Category      *ListingCategory    `form:"category,omitempty" json:"category,omitempty"`
	City          *string             `form:"city,omitempty" json:"city,omitempty"`
	From          *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To            *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
	OperatorMode  *OperatorMode       `form:"operator_mode,omitempty" json:"operator_mode,omitempty"`
	Size          *ListingSize        `form:"size,omitempty" json:"size,omitempty"`
	MinPriceCents *int                `form:"min_price_cents,omitempty" json:"min_price_cents,omitempty"`
	MaxPriceCents *int                `form:"max_price_cents,omitempty" json:"max_price_cents,omitempty"`
	Page          *int                `form:"page,omitempty" json:"page,omitempty"`
}

// GetPublicCalendarParams defines parameters for GetPublicCalendar.
type GetPublicCalendarParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// DeactivateAccountJSONRequestBody defines body for DeactivateAccount for application/json ContentType.
type DeactivateAccountJSONRequestBody = DeactivateAccountRequest

// CreateListingDraftJSONRequestBody defines body for CreateListingDraft for application/json ContentType.
type CreateListingDraftJSONRequestBody = CreateListingRequest

// UpdateListingJSONRequestBody defines body for UpdateListing for application/json ContentType.
type UpdateListingJSONRequestBody = UpdateListingRequest

// AddBlockJSONRequestBody defines body for AddBlock for application/json ContentType.
type AddBlockJSONRequestBody = AddBlockRequest

// UpdateOwnerOnboardingJSONRequestBody defines body for UpdateOwnerOnboarding for application/json ContentType.
type UpdateOwnerOnboardingJSONRequestBody = UpdateOwnerOnboardingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAccount Current account
	// (GET /account)
	GetAccount(c *gin.Context)
	// UpdateAccount Update visible name and phone
	// (PATCH /account)
	UpdateAccount(c *gin.Context)
	// DeactivateAccount Deactivate own account
	// (POST /account/deactivate)
	DeactivateAccount(c *gin.Context)
	// StartGoogleAuth Start Google sign-in
	// (GET /auth/google)
	StartGoogleAuth(c *gin.Context)
	// GoogleCallback Google OAuth callback
	// (GET /auth/google/callback)
	GoogleCallback(c *gin.Context)
	// Logout End the current session
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// ListCategories Listing categories (config)
	// (GET /catalog/categories)
	ListCategories(c *gin.Context)
	// SearchCatalog Public search (no login required)
	// (GET /catalog/listings)
	SearchCatalog(c *gin.Context, params SearchCatalogParams)
	// GetPublicListing Public ficha (no login required)
	// (GET /catalog/listings/{id})
	GetPublicListing(c *gin.Context, id openapi_types.UUID)
	// GetPublicCalendar Public calendar (no login required)
	// (GET /catalog/listings/{id}/calendar)
	GetPublicCalendar(c *gin.Context, id openapi_types.UUID, params GetPublicCalendarParams)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(c *gin.Context)
	// ListMineListings List the caller's listings
	// (GET /listings)
	ListMineListings(c *gin.Context)
	// CreateListingDraft Create a draft listing
	// (POST /listings)
	CreateListingDraft(c *gin.Context)
	// GetMyListing Get one of the caller's listings (private)
	// (GET /listings/{id})
	GetMyListing(c *gin.Context, id openapi_types.UUID)
	// UpdateListing Update a draft or paused listing
	// (PATCH /listings/{id})
	UpdateListing(c *gin.Context, id openapi_types.UUID)
	// ListBlocks Owner view of availability blocks
	// (GET /listings/{id}/blocks)
	ListBlocks(c *gin.Context, id openapi_types.UUID)
	// AddBlock Add an availability block
	// (POST /listings/{id}/blocks)
	AddBlock(c *gin.Context, id openapi_types.UUID)
	// RemoveBlock Remove an availability block
	// (DELETE /listings/{id}/blocks/{blockId})
	RemoveBlock(c *gin.Context, id openapi_types.UUID, blockId openapi_types.UUID)
	// PauseListing Pause a published listing
	// (POST /listings/{id}/pause)
	PauseListing(c *gin.Context, id openapi_types.UUID)
	// PublishListing Publish (or unpause) a listing
	// (POST /listings/{id}/publish)
	PublishListing(c *gin.Context, id openapi_types.UUID)
	// GetOwnerOnboarding Owner onboarding state
	// (GET /owner/onboarding)
	GetOwnerOnboarding(c *gin.Context)
	// UpdateOwnerOnboarding Update payout details and/or accept terms
	// (PATCH /owner/onboarding)
	UpdateOwnerOnboarding(c *gin.Context)
	// Readyz Readiness probe
	// (GET /readyz)
	Readyz(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccount(c)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAccount(c)
}

// DeactivateAccount operation middleware
func (siw *ServerInterfaceWrapper) DeactivateAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeactivateAccount(c)
}

// StartGoogleAuth operation middleware
func (siw *ServerInterfaceWrapper) StartGoogleAuth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartGoogleAuth(c)
}

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GoogleCallback(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCategories(c)
}

// SearchCatalog operation middleware
func (siw *ServerInterfaceWrapper) SearchCatalog(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchCatalogParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "city" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "city", c.Request.URL.Query(), &params.City, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter city: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "operator_mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "operator_mode", c.Request.URL.Query(), &params.OperatorMode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operator_mode: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", c.Request.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "min_price_cents" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_price_cents", c.Request.URL.Query(), &params.MinPriceCents, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter min_price_cents: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "max_price_cents" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_price_cents", c.Request.URL.Query(), &params.MaxPriceCents, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter max_price_cents: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchCatalog(c, params)
}

// GetPublicListing operation middleware
func (siw *ServerInterfaceWrapper) GetPublicListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicListing(c, id)
}

// GetPublicCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetPublicCalendar(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicCalendarParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicCalendar(c, id, params)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// ListMineListings operation middleware
func (siw *ServerInterfaceWrapper) ListMineListings(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMineListings(c)
}

// CreateListingDraft operation middleware
func (siw *ServerInterfaceWrapper) CreateListingDraft(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateListingDraft(c)
}

// GetMyListing operation middleware
func (siw *ServerInterfaceWrapper) GetMyListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyListing(c, id)
}

// UpdateListing operation middleware
func (siw *ServerInterfaceWrapper) UpdateListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateListing(c, id)
}

// ListBlocks operation middleware
func (siw *ServerInterfaceWrapper) ListBlocks(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListBlocks(c, id)
}

// AddBlock operation middleware
func (siw *ServerInterfaceWrapper) AddBlock(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddBlock(c, id)
}

// RemoveBlock operation middleware
func (siw *ServerInterfaceWrapper) RemoveBlock(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "blockId" -------------
	var blockId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "blockId", c.Param("blockId"), &blockId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter blockId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveBlock(c, id, blockId)
}

// PauseListing operation middleware
func (siw *ServerInterfaceWrapper) PauseListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PauseListing(c, id)
}

// PublishListing operation middleware
func (siw *ServerInterfaceWrapper) PublishListing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublishListing(c, id)
}

// GetOwnerOnboarding operation middleware
func (siw *ServerInterfaceWrapper) GetOwnerOnboarding(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOwnerOnboarding(c)
}

// UpdateOwnerOnboarding operation middleware
func (siw *ServerInterfaceWrapper) UpdateOwnerOnboarding(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOwnerOnboarding(c)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Readyz(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/readyz", wrapper.Readyz)
	router.GET(options.BaseURL+"/auth/google", wrapper.StartGoogleAuth)
	router.GET(options.BaseURL+"/auth/google/callback", wrapper.GoogleCallback)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/account", wrapper.GetAccount)
	router.PATCH(options.BaseURL+"/account", wrapper.UpdateAccount)
	router.POST(options.BaseURL+"/account/deactivate", wrapper.DeactivateAccount)
	router.GET(options.BaseURL+"/listings", wrapper.ListMineListings)
	router.POST(options.BaseURL+"/listings", wrapper.CreateListingDraft)
	router.GET(options.BaseURL+"/listings/:id", wrapper.GetMyListing)
	router.PATCH(options.BaseURL+"/listings/:id", wrapper.UpdateListing)
	router.POST(options.BaseURL+"/listings/:id/publish", wrapper.PublishListing)
	router.POST(options.BaseURL+"/listings/:id/pause", wrapper.PauseListing)
	router.GET(options.BaseURL+"/listings/:id/blocks", wrapper.ListBlocks)
	router.POST(options.BaseURL+"/listings/:id/blocks", wrapper.AddBlock)
	router.DELETE(options.BaseURL+"/listings/:id/blocks/:blockId", wrapper.RemoveBlock)
	router.GET(options.BaseURL+"/owner/onboarding", wrapper.GetOwnerOnboarding)
	router.PATCH(options.BaseURL+"/owner/onboarding", wrapper.UpdateOwnerOnboarding)
	router.GET(options.BaseURL+"/catalog/listings", wrapper.SearchCatalog)
	router.GET(options.BaseURL+"/catalog/listings/:id", wrapper.GetPublicListing)
	router.GET(options.BaseURL+"/catalog/listings/:id/calendar", wrapper.GetPublicCalendar)
	router.GET(options.BaseURL+"/catalog/categories", wrapper.ListCategories)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F3Nchu5dn6VU51URaq0qT9P1Vy5stDIo3tVsceOZa+GLgrsPiRx1QR6ADRlzpQe5lYWWeUFsvWLpXAA",
	"9B/REjWWZGcysxmKxO85H84/4N+STC5LKVAYnRz/lijUpRQa6Y8zqaY8z1HYPzIpDApjP7KyLHjGDJdi",
	"7+9a0s86W+CS2U//rHCWHCf/tNeMvOd+1Xs/KiVVcnNzkyY56kzx0g6SHCcnlVmgMHZUzGFaGRDSACsK",
	"eY15cpMmP0lzJiuRP/5S3qGWlcqQVjCjOW/S5INglVlIxX/FJ1jDa641F3OQCipxJeS1AI1a2x9pLaWS",
	"GWrNpgU+/mIucMksa2DFCp7T0DBjvLCMuUn96ASYkyyTlVtHqWSJynCHpIyVbMoLHv6+bR1+kNN2F7sm",
	"rsuCrSeCLWnPZl1icpxoo7iY2wac+NKDlRsLeA47Hz6cv9xN0s2O5UKK+JDaMFPRglFUy+T454QLu+IC",
	"DSZpwjLDV/ZDjvTRYjf5uDHDTZoo/KXiyiLnZ7vOeuTetsJa0i7BmiHl9O+YGbu0GJU2yF5W04LrRYQu",
	"xTVba5ixQiNwAWcHsCOvBSqQYiqZyi34uIazwxbFplIWyAiBCjWqFW4O/F5VCNcLFFAqOeMF2lECyYCJ",
	"HFhgiYaafv0JehQLs6X1hqIUyfMfCpldvcNfKtQREKLI9YTRDzOplvZTkjODzwxfYgwYCpk/QUv26RWK",
	"uVkkx4fP99MoUpS5z+i9LTb903qd0U2uGC8cx9e028hZU2iBeK+d3ps07rDVbauKUL3RrODacDGfbNm8",
	"IXgXVWcK8ZnBTwYIpM80zxFc41HyCNyg1bXWnkb5U683bdM8xrVTZnAu1fpUihmfx8Sj+/0u0fjKLSkM",
	"R2IRS6m5mSy5mGRBiy+54EsrsBqocmFwjoqow3/FLWe6sE371KlX64eKLSJKBSKSH3nwlH4RLQq+wq27",
	"vgzNW2TckoQdeHbEw/P9/f3U9g5fHBxGALpAtlpPCpyzYpJ5xd4ooJagtRQtkOUTi9vJQlZqi9VZcjIj",
	"1ZZ0eBOaO11oJE3BDS51VCv6L5hSjGhX8uyqKicZN+seMb7vkSKmfF1ngXy+mEq1kDKPDLLZTfEMJ2xp",
	"VUmEaQcxsrg+leDmLsK8tS0/2IYW+lVxt9ESUE1tLY24caZZayMHh11yPL9LDLlBumhL28evTfk4KTu7",
	"jpKtj/045lqgih3tl7UB5O2S4eNtRaBakj7+xKxdkBwbVeGdRkDoGJvema6RuXLsTJRUbSs+AqulNarn",
	"EbvmlcxYYXvBoloyAaHh8BiTK1x3J7dTj25fwcaecztFM1l77Bgh/oasMIt33onbpIi1o3jWI0rGhEGu",
	"5IAmDRZw3V5ebWPO2G6xJfqT8qCC//eYPN+OsthWO/TdVEdusKcHZlLBJfW7hEBIb4c7kxnzUdSS39Iy",
	"e2o9RHbexPsK25qPEeXVpdn5ks0RPrx7ZR1rbaQln0MmXOF6NLDxczfYwX013xPpuv2vrevubU86sbJ1",
	"H2p7m07doFhV5veUBzEHYAODYd3pw2jmWgI9nJL2JyAw8g6t3ZekrTjHkomKFdbZKTAzimfkEM0XZpJJ",
	"oY2qMr9nNlc8qwpTKWpOIigSA6kne9kSu31tvUIVVb6N+xdIBkwhewFCime4LI0XdSjYtOgIuraHS7/F",
	"rOwe70PLtFnRLcR705Jx3f1YnhTriWIGtz21PEdhvDC57WSESc9Dey+hN+Vy1BBeertomyle27Z9EtEA",
	"txDlrWdjlyC1UK4/3CqXrN7KgrUQczv8JBHhZ02kIJU2fzbSsCL2U2+XpbO5mtFC19Tv4BYKvAuCtEuC",
	"XGbVEoWZNPPEvD78VKLiKDK8o6FluifDkn3yLD9ybsYtODOKrbCYKLTnIzODx2JodxeetkFakGTY5vRf",
	"BLkfeuaKzUwT2KNjV7JKRwOpabIB/E2Q6QnJ7dtCk2aBEAQjcE1/+2iPCzDFTaXByPNQALmHp16It15p",
	"DEad49eil3B9JW2KoFjPEKWXneBNHdKNRIjZWlZmcsVFJHr+pmS/VAiuDdg2sIOj+QhK/imFKRNXu1FZ",
	"6wctmDbP4wRzDTSaOKwNqqW2mhdLMwT9bpt7mf6u6wpVL+4ywLfWajeW1h8sxsvGwmox0opqq9ZZ/Lw4",
	"6XfKChQ5iyiXaSGzq64w/cJg91NFsPti/J4h4gFH5A5R3onlxk0nT9EoAzuq6FtxXCe3mDQRH/VOv/T3",
	"xvi35Ehji06iltEt7e9vrzxIIHNb/21Lh+3/nJNW+1tb+Ep3OkTegPrm/KI7czfvkOXr4YjaI0QMe9l3",
	"Y0858IPvBdgGaSsSp+zaRrF4XPpFoT6vo2j4JE2EtAar/fxxy8DffWKWH8hZvytu3E//N3s6EczOcr+s",
	"Q7DYmmH+9bvvDg7+Ev7rjnh0eMeIPSpEk/rDe/8zJfb/KyX2ZxLsjiTYwDnpeTOD58VZ5xOyzOMY6rk9",
	"9/dgtnAhepsgkZxVipv1haVXCHrJK44nlaEiHW4FvvsqCf5mLbMnoQKsgVvJ/x3XrmSLi5kMpWAsI6L4",
	"/qeNzK9UkRwnC2NKfby3FwYeTRUKKUZZIat84ygnZwdwagc9BheeylmO8Fcp5wWmUKKa8QKWn/9b8KVM",
	"oZBz6ysi5KiZ4Sv2+b8+/6ccjcXZIZwy8/kftsGxS0pkTKUwrXTGoPz8P/RF6vzyXCrIMSuY/ZiORUZ+",
	"0Od/KC4hR7DiVQo+5YVbDMKMZ4tmlNFYXOASXNkQS6Fkc7ZEYSTICi6M4qVdH5RK5pWxi6PgZoZewXu6",
	"vT5/3wJxTUY4eXuepEnN+mR/dDTa9zJGsJInx8nRaH90RJEMsyA277GmMm7uvN5+NsdUSrhQRMaKAlUo",
	"lBrBT7hCBVxkRZWj9qQHXRGw0rHAJeNFClKBNAvbktg046g0THEtRU7DOpqHuiy3aycWuRTneXKc/BVN",
	"qOBLu5Wgh/v7D1ZnGKaIVBqeVkqhMGHrlqjP9w+GBqxXuNcpzmyftOT45+4Z+/njzcc00dVyyaxS3Jgx",
	"TQyba6vDwzcfSRyYLFJF9yOFni1cLPFJywPXoNAyBvMRnLrCNy7mMJVmAUt2hcTjsQhlcFjwObcGnpEe",
	"sAg7Z0e7I3jrQmK2szZsrYE8VMxh5+xwN8a+jiHlI0OozQ8yXz8Y86LG2k3X/jGqwpuvAyC3vPwLAWQ7",
	"Hd3dqSmPtj0OD7eZpl24ey+gup3BimtCC4GOiRxCNHETtjdpLXb2mgJV0pZSR0TQuVJIUo3cDQGrgxF4",
	"ja6hQLaqRYhGprKFxSFwsWKKM2EsIs/Fs1LJuUJtD4EwrNDAlCukzpjIsCgIvkfdbj6TrcGXePybBVAM",
	"4BtVJo8E8sFqlm8H6M0SHwDsjwzdZq0gr8WtopYwW5nF3pyU3C3qMucKM6Ot2HQKcQRvRLEO2tE59RoY",
	"rA5qTWoRalCpqrRkkwoUziqNuQWetlog9BLISZMGIS2kCvX3MVxeGKaMm5go0IPE0f7h8A6aDbj8SY7O",
	"nXklHWS6aOlbmZZg3zlZ9bh3AELCxZoPK54j5U3oXFNJa6WC4q25TkSpjRU+F8+4aPPcEmqD4XvW9pky",
	"V9Yc5fyPn7IFE3PHWlbwvOa4zDGtOUjMtQaZM6k8I9Ox0GhsV89NcLhNSZSqNqhsr2ucAivL0Vj8R4Vq",
	"DSVTbKnh0k51mcIlVQNcus6XaEl3SfJOIcthpuSSRvnw7tVoLN4vELQV2l3zDQQZdw1cNWayqZIfjcUJ",
	"5Jtn3ZkZdn+Ygza8KNqtorYdTXsayHtfiLbI8ftw2sGGp8Ebe1oga9Y0BA7nVQyrrh9FroF1rhBZH1Dr",
	"EbyU6IDa0KeNiLGwzMtDowXP61SgjpHxlVvJhtB/HgnceYihyINR8aim7I/ezs+8SdtyFzfJmjHDCjnf",
	"86El7zhv4ZpQN5AzaHqm3jexlqpt5ANH4AMRY1FahIeitB0KVOxCUKNUuub9QTMgYK0Zctqs9AtV7lbl",
	"B72S/Y0YT8R5aRbYRbs3oloUgx0nNndbzPGk7fEnYHGQOxfOFqvz5w164aIqS6mMhhkvDDmD65oNKWTc",
	"rNOxIKuSW7W4YgXsKGK2XW0Yh85FcD1YpqR2ULBHTeFYhL67aZNTX5IsplATKCutSURq/ivCDtUKWPlM",
	"AT9r/71lJM4VwsEzLnL8hDlcc7MABjNu/yjZHKl3VPkSAU499ayvptgSDYmnn31I5ZfKpRPqiEqTlthK",
	"LW4EVm/SgZFdXmNYEA70s8qi06+TCozlXuPjGPkQo3QTb9sSqV8xFB/b54HuRfdwCyU+4pKLiYtqhhxQ",
	"M/htQeHB8dinBx3PlxE1g+Q4Y1VhKEB7W7DWivdH8y3alVoRYWa/t1Lee3y1GOpKtrddf1BIKOSci1q2",
	"by/f9n7j+c1WKsivyEX8rO5gm8Jv5KJ82lXzjEWoqyMx1FT++G/3fMz0BUjrQbQm8T+MxYxjkcNOyT/B",
	"Fa5T53Xv+hil9SVEq5u7Icu1tSZyFGNRCcMLODsaiLl1ywsekee9kroI11u0dRbL87stlvpmdhQbjk/b",
	"QiMuvktGTpU/T5Rv7jrhUZkXr1e4+TgIv72sVW5zJw5tV3tCOgq0W0vGNVSCuRubBaZjURaVa+GPfQhR",
	"E2AK6zUYvqTgC6W1WtarwhWyYiyuF3WYMAcm1vXMt2KrriPaSj1+JWX08dGRX5NhGPo1BB4G/WG4b+4A",
	"LOii0K93Iv1wf7+pmfzb+/dvwYeB6P52wVfWJqtRmi0wuwLrzFHU2lUgRP2ov/n5H5HnvbtQsUcn7Po3",
	"jPUVCru/UslpO7AqS+111502eSAeUql6u7I0tzY4uZ99Z9WHJxTOmcoLuwA5AwowjOCD9m4SFa7SNf2c",
	"6QXlQYfcpddchLqCp3GYBiu1N+leR5U7JHFprydwlO30rRn/RTfmTcPu+is6k9Gow2kdtKkFvoBLqmi+",
	"HMFL+/8m/h0C99zfyMrGwplNI3hfc3VZaQOaGa5n62DVwJwm2aEyhDQ412PhVUgKvlgiJExJl9CRJQcr",
	"7ds7M89nq0tQdOqgg0xJfWStvm0RLkK4ccPXY8F1bQKloUw4R8N4oZ2pRbuiXPkuTHEmFbYV5FhkTMBS",
	"rij7dVmbcZZ6mzEvDRkTJGWI7mMRWPSiaWHdRruIeJrEDgAlKm0BwMaCWEWPzfiRA8m5iR2rzv31l75w",
	"/THyD9GL8lvlHg4e2j+I5h6IbL5s7g+UYnNkBwYOF0VtkEdkQlsPbO+7BDlB0Y1ZVRS1NDesFUQLZ7Ln",
	"uHhvBHbITaHEhRedNMrugAn4ev0ErsUtcGkphqcCyv0Nt20x8lc0YCWJnMU1COyUisTW7qAueXT7brBe",
	"weWQ68UCebUarhfcKSavu0AquHSXcC5HcNK417XIDfJyioA5tzLaLJSs5gswC64BRV5KLsyLlsFiVdtY",
	"0KjADcy40ial3sBNahvWV5WBzRkXwxUObTg/VoXD7xG+T3KaQoVD8a2fKtvhL4+fmHzV+No1Tl9AjTNv",
	"dFicBWo9TaFG0CJSucXk99Qne80Nny18DNZ6FsoF64N+7qgI70pM12MRcSWsEbZkwtp5XraR7zrkYfzg",
	"FvgUvsXmq1dbeBl+fX8ItUOVr7DieG01zya39VfVNlHv6CTPrWvkwOgzyI368NACxyTn+FiNYh2NgpVj",
	"sdOGYLikqbmg3Ll7n7FHiRdwdgTXvCjGYiGFrJRTRnWpEUjRjrdFzaXwhtwj6Zb+E3VPbNNHjtHAsfka",
	"1v03qV4cNTwqrVML+MmDeBoE0WNrlJM8txNvnvr7qZK93+j/585XyZEesYzoFeuPNyc3rkbeMu2Twi7C",
	"cYWlGYsQomKVNesKOY8dMTdBc8ruKqNwHFDUK/9jSHNHgvvw9AkEeRod1EPmywPOXUSSSeTun38t/fTW",
	"LkHHs4fnvsCKMOcquTqlr2MxrYz32jWUISETOrpyI3u+ouFZmvmb8Mm9afqnE9E4Ea0w4H3jysTXGKC2",
	"ldOt53q/3rl47cX/gPsCXPRjtSdFEfY8Fi5abXUCrlhRke6g0+FebR3BST2SWTBDD0lrymTOKajrrjpw",
	"AdzoppTNMP96sPJuz/PDQxdFc9lU91o2xTPGIpM5aqujKu2Z2ipspxqoonDzt2IVw0EHfw/jGzmwNbZ2",
	"6G1wx5zdb/oEP7J55PnTJshuk5MZPntkyuzJzuMot7ra1wukqvDGdV4wDRpNLPURXghpe9qUCBnBD3QV",
	"yHo8U3Sv97VSI64lJSrCkar3MhDg7T/y8ogI7U8VQeqb/jPiOrzf9shpvYGJB+2pW0OkrXemWyNajT+C",
	"CzR0Fi/b90zp0srlWCjMpMrrqnMsDRMZUl2HNmxZEjic4VxXDNF59qVKNBj424VWiHWRpTC8W8g0SPc+",
	"j5PpVmiOxeoAdtzUpmJFuOx4KoXAzFCxyNynCAsmchK0Z0e33CaLYeuxYq4D13ufOPb6eyDu3xv8Zm/g",
	"+Jjkppjak8qj1AmnYWlJ7z/co16kXwRST6PYbMYzuvbluny3f+Qurl5zjSMgI80utZAsd4ifo0DFMyqi",
	"eXnx097b83ML2eaFjUv/xsQlzGRRyGsNJzTbs1dMzCs2R9hBkUJpnv3wLgXUtvdLV4VpzyJz/0wB/Rx3",
	"WWnvjwi67iMj0X+UhOX0ssBD3va5c9afqPKMZr7pOrAs57dVyfj3R4L5GnkZpXMb/Xhvj9iwkNocf7//",
	"/X5i8evH3OjuK3RSWhoto126rBPryna7+PsmnWxqcz3Cd6XbEZt93/p/x4LuiYSqhG7H+v7db1FBcfru",
	"w0sq32mShO7f1fD9m+Lazcmd15lzTSUY67QJidr1+OLKzmihluzm483/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
