_format_version: "3.0"
services:
  - name: canteiro
    url: http://canteiro:8080
    connect_timeout: 10000
    read_timeout: 60000
    write_timeout: 60000
    routes:
      - name: canteiro-path
        paths: [/canteiro]
        strip_path: true
        protocols: [http, https]
    plugins:
      - name: key-auth
        config:
          key_names: [apikey, x-api-key]
          key_in_header: true
          hide_credentials: true
      - name: rate-limiting
        config: { minute: 120, hour: 2000, policy: local, fault_tolerant: true }
consumers:
  - name: canteiro-server
    keyauth_credentials:
      - key: "REPLACE_ME_WITH_OPENSSL_RAND_HEX_32"
